### ISSUE TITLE
error in alpine image

### ISSUE THREAD

**Issue by yanns** [GoogleCloudPlatform/cloud-sdk-docker#102]
When using the alpine image, I see the following logs:
```
You do not currently have this command group installed.  Using it
requires the installation of components: [beta]


Your current Cloud SDK version is: 174.0.0
Installing components from version: 174.0.0

+---------------------------------------------+
|     These components will be installed.     |
+----------------------+------------+---------+
|         Name         |  Version   |   Size  |
+----------------------+------------+---------+
| gcloud Beta Commands | 2017.09.15 | < 1 MiB |
+----------------------+------------+---------+

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Do you want to continue (Y/n)?
ERROR: (gcloud) This prompt could not be answered because you are not in an interactive session.  You can re-run the command with the --quiet flag to accept default answers for all prompts.
```

**Comment by ahmetb** [comment]
This is expected. Alpine and slim images do not have additional components installed. You can extend the image by installing them yourself or use the full image.

**Comment by yanns** [comment]
Thx for the info.
But the slim image can start.
The alpine image cannot even start.
Is it expected?

**Comment by ahmetb** [comment]
@yanns doesn't sound like it, what command are you running to run the container image?

**Comment by yanns** [comment]
Here is the content of the `docker-compose.yml` file:
```
pubsub:
  container_name: pubsub
  image: google/cloud-sdk
  command: gcloud beta emulators pubsub start --host-port 0.0.0.0:8042
  ports:
    - "8042:8042"
```

**Comment by ahmetb** [comment]
@yanns your compose file doesn't say you're using `alpine`?

I just ran `docker run --rm -i -t google/cloud-sdk gcloud beta emulators pubsub start --host-port 0.0.0.0:8042` and it works fine for me.

The :alpine and :slim images do not have additional components installed (i.e. in this case `beta`). You need to derive a new image and install them manually, or use the full image.

**Comment by yanns** [comment]
Yep, sorry, copy/paste error 😉 

I was just surprised that the alpine shows an interactive terminal, but the the slim not.
If it's ok for you, it's ok for me. 😄

**Comment by ahmetb** [comment]
Sounds like a bug with entrypoint, please feel free to open another issue.
