### ISSUE TITLE
Auth service account during docker build not working

### ISSUE THREAD

**Issue by ericuldall** [GoogleCloudPlatform/cloud-sdk-docker#105]
I'm trying to build some images that are pre authed using a service account and it doesn't seem to be working as expected.

**Dockerfile**
```
FROM google/cloud-sdk:latest

ENV GOOGLE_PROJECT [PROJECT_REDACTED]
ENV GOOGLE_CLIENT_EMAIL [EMAIL_REDACTED]
ENV GOOGLE_CLUSTER_ZONE [ZONE_REDACTED]
ENV GOOGLE_CLUSTER_NAME [CLUSTER_REDACTED]
ENV GOOGLE_APPLICATION_CREDENTIALS /root/service_key.json

COPY .keys/${GOOGLE_PROJECT}_service_key.json /root/service_key.json

RUN gcloud config set project $GOOGLE_PROJECT

#This auth seems to happen successfully
RUN gcloud auth activate-service-account --key-file /root/service_key.json

RUN gcloud config set compute/zone $GOOGLE_CLUSTER_ZONE
RUN gcloud config set container/cluster $GOOGLE_CLUSTER_NAME

# This returns empty auth list??
RUN gcloud auth list

#Next line fails when uncommented since no auth is working
#RUN gcloud container clusters get-credentials $GOOGLE_CLUSTER_NAME
```

If I exec into the built image and run the `gcloud auth activate-service-account` command again...it works as expected. For some reason it's not saving the credentials during the build.  I'm wondering if this is perhaps introduced by the `VOLUME` declaration in the base docker image. Even though i'm not mounting a volume to that path will docker still clobber any data put there at build time?

**Comment by ericuldall** [comment]
So, after a quick review of the Docker docs it seems my suspicion is correct...

> **Changing the volume from within the Dockerfile**: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

I'm wondering if I redeclare the `VOLUME` in my Dockerfile, that would solve the problem. Trying that now and will update on results.

**Comment by ericuldall** [comment]
After updating my Dockerfile it does not seem to remedy the issue...

**New Dockerfile**
```
FROM google/cloud-sdk:latest

ENV GOOGLE_PROJECT [PROJECT_REDACTED]
ENV GOOGLE_CLIENT_EMAIL [EMAIL_REDACTED]
ENV GOOGLE_CLUSTER_ZONE [ZONE_REDACTED]
ENV GOOGLE_CLUSTER_NAME [CLUSTER_REDACTED]
ENV GOOGLE_APPLICATION_CREDENTIALS /root/service_key.json

COPY .keys/${GOOGLE_PROJECT}_service_key.json /root/service_key.json

RUN gcloud config set project $GOOGLE_PROJECT

#This auth seems to happen successfully
RUN gcloud auth activate-service-account --key-file /root/service_key.json

RUN gcloud config set compute/zone $GOOGLE_CLUSTER_ZONE
RUN gcloud config set container/cluster $GOOGLE_CLUSTER_NAME

# This returns empty auth list??
RUN gcloud auth list

#Next line fails when uncommented since no auth is working
#RUN gcloud container clusters get-credentials $GOOGLE_CLUSTER_NAME

VOLUME ["/root/.config"]
```

Same issue persists. 

Is it absolutely necessary to specify the mount point in the base image? It seems like an unnecessary step that, in this case, is causing some unexpected behavior. It's simple enough for an end user to extend the image and add the `VOLUME` declaration if they *NEED* it...however since there's no way to retroactively remove it, perhaps it is best left out.

**Comment by ahmetb** [comment]
It's not good practice to copy credentials into container images. I recommend providing your credentials as a volume in the runtime. Try something like:

```
docker run -v /path/key.json:/data/key.json --entrypoint bash google/cloud-sdk \
  -c "gcloud auth activate-service-account --key-file /data/key.json && \
        gcloud OTHER_COMMAND"
```

> Is it absolutely necessary to specify the mount point in the base image?

I think we advised users to:

```
$ docker run -ti --name gcloud-config google/cloud-sdk gcloud auth login

$ docker run --rm -ti --volumes-from gcloud-config google/cloud-sdk gcloud compute instances list --project your_project
```

So I am guessing removing the VOLUME declaration in a new image might break the backwards compatibility for users with existing `gcloud-config` container storing this volume. (Feel free to validate this.)

**Comment by ericuldall** [comment]
Is it in the scope of this image to have an opinion about its implementation?

**Comment by ericuldall** [comment]
> So I am guessing removing the VOLUME declaration in a new image might break the backwards compatibility for users with existing gcloud-config container storing this volume. (Feel free to validate this.)

Removing the `VOLUME` declaration does not prevent a user from mounting a volume using `-v, --volume` arguments. It seems all it does is make sure that path is empty (or at least doesn't contain any data added after declaration) at runtime.

**Comment by ahmetb** [comment]
@ericuldall take a look at our recommended way of running this as a development tool interactively:

- docker run -ti --name gcloud-config google/cloud-sdk gcloud auth login
- docker run --rm -it --volumes-from gcloud-config google/cloud-sdk gcloud compute instances list --project foo

This currently works today and without specifying `-v`/`--volume`.  Removing the VOLUME directive will cause this not to work because the VOLUME serves as an identifier where the volumes are (so it actually does more than just making sure the path is empty). :)
