### ISSUE TITLE
Addons are installed using latest available; not the specified CLOUD_SDK_VERSION

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-sdk-docker#114]
@salrashid123 can you please take a look?

I'm trying to build the `Dockerfile` at 181.0.0 but while building I realized additional components are installed at the latest available version such as 182, 183, 184...

```
...
Get:3 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk all 181.0.0-0 [14.1 MB]
...
Get:122 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-app-engine-python all 183.0.0-0 [4215 kB]
Get:123 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-app-engine-go amd64 183.0.0-0 [59.4 MB]
Get:124 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-app-engine-java all 183.0.0-0 [120 MB]
Get:125 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-bigtable-emulator amd64 183.0.0-0 [1975 kB]
Get:126 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-cbt amd64 183.0.0-0 [2968 kB]
Get:127 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-datalab all 183.0.0-0 [18.2 kB]
Get:128 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-datastore-emulator all 183.0.0-0 [18.4 MB]
Get:129 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main google-cloud-sdk-pubsub-emulator all 183.0.0-0 [33.7 MB]
Get:130 https://packages.cloud.google.com/apt/ cloud-sdk-jessie/main kubectl amd64 1.8.4-00 [8612 kB]
```

This means our older builds are not reproducible when an new version of gcloud (and its addons) releases.

Should we add `=${CLOUD_SDK_VERSION}-0` to the addons as well?

**Comment by ahmetb** [comment]
I was able to add this to all addons (except kubectl, that one is not managed with the same versioning schema). Rolling out in `182.0.0` tag.

**Comment by salrashid123** [comment]
@ahmetb 
interesting.  I didn't think the additional packages would pickup latest (just assumed it'd match base automatically)

i'll file an internal bug tomorrow to see if the subpackage installers could/should check and match base google-cloud-sdk

**Comment by ahmetb** [comment]
@salrashid123 thanks, please cc me.
