### ISSUE TITLE
gcloud sdk 187.0.0 was released

### ISSUE THREAD

**Issue by milkcocoa** [GoogleCloudPlatform/cloud-sdk-docker#120]
https://cloud.google.com/sdk/docs/release-notes#18700_2018-01-31

**Comment by ahmetb** [comment]
We're not actively keeping up with each release for now in the docker images.

Do you need timely updates? What's your use case?

**Comment by milkcocoa** [comment]
I understand the current situation of updating the docker images. We don't use the latest features of SDK, so we don't need timely updates.
