### ISSUE TITLE
i keep getting an error that APK's not found or not accessible

### ISSUE THREAD

**Issue by renperez** [GoogleCloudPlatform/cloud-sdk-docker#126]
[Step 4/7] Uploading [/Automation/Android/Daily/GradleBuild/Test/test/build/outputs/apk/test-googleFlavor-testFree-armv7a-debug-239999.apk] to Firebase Test Lab...
[19:07:04][Step 4/7] ERROR: (gcloud.firebase.test.android.run) [/Automation/Android/Daily/GradleBuild/Test/test/build/outputs/apk/test-googleFlavor-testFree-armv7a-debug-239999.apk] not found or not accessible
[19:07:05][Step 4/7] Process exited with code 1
[19:07:05][Step 4/7] Process exited with code 1
[19:07:05][Step 4/7] Step Run Firebase Test Lab Auth (Command Line) failed

Not sure why I keep getting this error when the APK's is definitely inside this directory.

**Comment by renperez** [comment]
nevermind. found the issue

**Comment by CrashHunter** [comment]
@renperez what's the issue and how to solve it?

**Comment by fabiochoupina** [comment]
@renperez How did you fix the issue?

**Comment by kaskasi** [comment]
@renperez I am having the same issue. Could you please explain how you fixed the issue?

**Comment by zhurkov-antichat** [comment]
Had the same issue on Mac, did following:

1. Specified absolute path of file
2. Enclosed file name into `""`

So as a result it was `gcloud ... --app "/Users/user/.../my_apk-file.apk"`

**Comment by badredaha** [comment]
Make sur you put just one './' not '../'
ex :  "./app/build/outputs/apk/dev/release/app-dev-release.ap"
