### ISSUE TITLE
cloud sdk 196.0.0 was released, with some breaking changes

### ISSUE THREAD

**Issue by kri5** [GoogleCloudPlatform/cloud-sdk-docker#128]
As mentionned in the changelog of 196.0.0, the `gcloud docker` command is being deprecated in favor of `gcloud auth configure-docker` (https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker).

It would be interesting to have a release for this version.

Maybe having releases for the various future versions which introduces breaking changes?

**Comment by ahmetb** [comment]
@kri5 actually I released 195.0.0 yesterday.

Here are some things you should know if you are using this image:

1. We are releasing the docker image on a best effort basis: So sometimes we skip versions and some versions never get published. Often we are late to publish image of a version.
2. You should pin yourself to a version (do not use :latest).
3. If you really need a new version like 196.0.0, open an issue and I’ll work on it to have a Docker image released for it. Most of the time users don't ask for this.

Do you need 196.0.0 right away?

**Comment by kri5** [comment]
I never use :latest tag, but always pin a version.

I thought images were built through an automated process.

And i need the 196.0.0 docker image version, this is why i opened this issue

**Comment by ahmetb** [comment]
Got it. Just tagged 196.0.0.
