### ISSUE TITLE
Please automate builds

### ISSUE THREAD

**Issue by chrishiestand** [GoogleCloudPlatform/cloud-sdk-docker#130]
Currently the latest docker image is SDK version `198.0.0` on docker hub <https://hub.docker.com/r/google/cloud-sdk/>. It's typical that a serious project like this will have automated container builds. Whereas the latest gcloud SDK release is `203.0.0`.

One use case: I'm hitting a potential bug with this docker image and I cannot easily try the latest to see if the potential bug has been fixed in the meantime. `gcloud components update` doesn't work inside the container because my user is not root.

**Comment by ahmetb** [comment]
This is on our roadmap. For now we're manually refreshing the images based on demand.

I'll publish 203.0.0 manually now.

**Comment by ahmetb** [comment]
Done.

cc: @GoogleCloudPlatform/cloud-sdk for visibility on requests for automating builds.

**Comment by chrishiestand** [comment]
Thanks @ahmetb and I'm looking forward to the automatic releases.
