### ISSUE TITLE
Unable to retrieve Application Default Credentials on GCE Ubuntu > 16.04

### ISSUE THREAD

**Issue by GuillaumeLachaud** [GoogleCloudPlatform/cloud-sdk-docker#132]
I am using the google cloud sdk and the `gcloud` command inside one of my docker container running  on GCE to upload some artifacts to a google cloud storage bucket. For some reason, on ubuntu 17.10 and above, the cloud sdk seems to fail to retrieve the default application credentials through the metadata service as it should (https://cloud.google.com/docs/authentication/production).

In order to understand what's happening and to rule out environment issues,  I started some tests using the `cloud-sdk-docker` image.

Running `docker run -ti  google/cloud-sdk:latest gcloud info` on a brand new Ubuntu 16.04 GCE VM correctly returns information about the service account and the current project, without me providing any sort of login information. If I understand the Application Default Credentials (ADC) strategy outlined in the documentation, this is because after failing to retrieve the crendetials locally, it fetches them from the metadata service. Note that running `gcloud info` on the VM also return the same info correctly. I have a few of these VMs where I can reproduce this behavior consistently.

However, running the same on a brand new Ubuntu 17.10 or 18.04 GCE VM doesn't work. I have a few of these VMs, have even tried to create some new from scratch and can reproduce consistently. Running `gcloud info` directly on the VM works, it gives me the account info without asking me to login. But `docker run -ti  google/cloud-sdk:latest gcloud info` "fails" in the sense that it doesn't retrieve the account credentials:

```
Google Cloud SDK [203.0.0]

Platform: [Linux, x86_64] ('Linux', '36e6f8e7b90f', '4.13.0-43-generic', '#48-Ubuntu SMP Wed May 16 12:18:48 UTC 2018', 'x86_64', '')
Python Version: [2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  core: [2018.05.25]
  app-engine-python: [1.9.70]
  pubsub-emulator: [2018.05.25]
  app-engine-java: [1.9.63]
  datalab: [20180503]
  beta: [2018.05.25]
  gsutil: [4.31]
  cloud-datastore-emulator: [2.0.0]
  cbt: []
  alpha: [2018.05.25]
  app-engine-go: []
  bigtable: []
  bq: [2.0.34]
System PATH: [/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
Python PATH: [/usr/bin/../lib/google-cloud-sdk/lib/third_party:/usr/lib/google-cloud-sdk/lib:/usr/lib/python2.7/:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload]
Cloud SDK on PATH: [False]
Kubectl on PATH: [/usr/bin/kubectl]

Installation Properties: [/usr/lib/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/root/.config/gcloud/configurations/config_default]

Account: [None]
Project: [None]

Current Properties:
  [metrics]
    environment: [github_docker_image]
  [core]
    disable_usage_reporting: [true]
  [component_manager]
    disable_update_check: [true]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2018.06.02/05.33.21.505897.log]

git: [git version 2.1.4]
ssh: [OpenSSH_6.7p1 Debian-5+deb8u4, OpenSSL 1.0.1t  3 May 2016]
```

Am I doing something wrong ? I can reproduce this on vanilla VMs, fetching docker from the ubuntu repos. I don't add any specific configuration and the `docker run -ti  google/cloud-sdk:latest gcloud info` is the only thing I run on these VMs. Docker is that the same version on both the working VMs and the non working VMs: `Docker version 18.03.1-ce, build 9ee9f40`. They are also assigned the same service account.

Is there any documentation somewhere that would explain this difference in behavior and that I would have missed ? Is there a better way to provide application credentials to gcloud running inside my docker container on a gce vm ?

**Comment by salrashid123** [comment]
sorry, just noticed this.

gcloud will use `ADC` but will try to acqire it from various places.  One of them is from GCE's metadata server at link-local address `169.254.169.254` (or ```http://metadata```)

I wasn't able to repro the issue but can acquire an access token and render the metadata's service account from docker on ubuntu (if i allow it access to the host interface `--net=host` as shown below


using
```
$ uname -a
Linux instance-1 4.15.0-1017-gcp #18-Ubuntu SMP Fri Aug 10 10:13:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```$ docker version
Client:
 Version:           18.06.1-ce
Server:
 Engine:
  Version:          18.06.1-ce
```


first run
```
$ docker run -ti google/cloud-sdk:latest gcloud config list
[component_manager]
disable_update_check = true
[core]
disable_usage_reporting = true
[metrics]
environment = github_docker_image
```


then use `--net=host`

```
$ docker run --net=host -ti google/cloud-sdk:latest gcloud config list
[component_manager]
disable_update_check = true
[core]
account = projectnumber-compute@developer.gserviceaccount.com
disable_usage_reporting = true
project = your-project
[metrics]
environment = github_docker_image
```

you can even ask for the access token directly

```
$ docker run --net=host -ti google/cloud-sdk:latest gcloud auth print-access-token
ya29.cREDACTED
```

HTH

**Comment by salrashid123** [comment]
pls reopen if this is still an dissue w/ the repro;
