### ISSUE TITLE
Update to 209

### ISSUE THREAD

**Issue by beldur** [GoogleCloudPlatform/cloud-sdk-docker#141]
What is the update interval.

Current Docker Image has sdk Version 206
Latest sdk Version ist 209

**Comment by mckingho** [comment]
+1. Any schedule to update image version?
I need an updated image with SDK 211 and alpha 2018.08.03.

**Comment by nrvnrvn** [comment]
@ahmetb 🙏

**Comment by salrashid123** [comment]
I've  pushed  the `213.0.0` version forward and will try to track the release via announce here and push them as they happen

https://groups.google.com/forum/#!forum/google-cloud-sdk-announce

The push/release is pretty manual now on our end; we're checking if there is a reliable hook to trigger builds off of (or use a daily poll  and compare the latest SDK that out vs what `:latest` provides (if different, then auto-build and push)

I'll close this issue out but will open up a new issue once we settle on automation.
