### ISSUE TITLE
gcloud beta function bug 

### ISSUE THREAD

**Issue by haifabenaouicha** [GoogleCloudPlatform/cloud-sdk-docker#142]
Hello,
While writing a CI runner to deploy a http cloud function in python : 
""""
deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud beta functions deploy ${FUNCTION_NAME} --memory ${MEMORY} --region ${REGION} --stage-bucket ${STAGE_BUCKET}  --runtime ${RUNTIME} --trigger-http

  <<: *tags_rlt
""""

I got the following error : 
ERROR: (gcloud.beta.functions.deploy) unrecognized arguments:
  --runtime (did you mean '--timeout'?)
  python37

I am aware that the google/cloud-sdk doesn't have the latest version of gcloud and that gcloud beta functions need that latest one. but I don't know which command to use in the script level of the deploy stage above. Any ideas please how to fix this.

**Comment by vladkras** [comment]
why closed without any response? same problem with cli (ubutnu)
