### ISSUE TITLE
dev_appserver.py doesn't pick up grpc reference

### ISSUE THREAD

**Issue by cthrax** [GoogleCloudPlatform/cloud-sdk-docker#145]
This may be the wrong place for this issue, but I thought I'd start here as this configuration works in my host machine just fine.

When running dev_appserver.py and enable support for datastore emulator, I get the following stacktrace:

> api_1                 | Traceback (most recent call last):
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 96, in <module>
> api_1                 |     _run_file(__file__, globals())
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 90, in _run_file
> api_1                 |     execfile(_PATHS.script_file(script_name), globals_)
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 515, in <module>
> api_1                 |     main()
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 503, in main
> api_1                 |     dev_server.start(options)
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 258, in start
> api_1                 |     configuration.modules[0].application_root)
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 649, in create_api_server
> api_1                 |     if options.support_datastore_emulator else None)
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/stub_util.py", line 190, in setup_stubs
> api_1                 |     datastore_grpc_stub_class(os.environ['DATASTORE_EMULATOR_HOST']))
> api_1                 |   File "/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/datastore_grpc_stub.py", line 82, in __init__
> api_1                 |     raise RuntimeError('The DatastoreGrpcStub requires a local gRPC '
> api_1                 | RuntimeError: The DatastoreGrpcStub requires a local gRPC installation, which is not found.

I'm using this docker base:
```
FROM google/cloud-sdk:213.0.0-alpine as api_base
RUN apk add --no-cache curl unzip openjdk8 mysql mysql-dev build-base py-setuptools python-dev libxml2-dev libxslt-dev netcat-openbsd py-pip
RUN gcloud components install app-engine-java app-engine-python app-engine-python-extras cloud-datastore-emulator beta
```

and see this when building the image:
Your current Cloud SDK version is: 213.0.0
Installing components from version: 213.0.0
```

+-------------------------------------------------------------------------+
|                   These components will be installed.                   |
+------------------------------------------------+------------+-----------+
|                      Name                      |  Version   |    Size   |
+------------------------------------------------+------------+-----------+
| Cloud Datastore Emulator                       |      2.0.1 |  17.4 MiB |
| gRPC python library                            |      1.9.1 |  12.1 MiB |
| gRPC python library                            |            |           |
| gcloud Beta Commands                           | 2018.07.16 |   < 1 MiB |
| gcloud app Java Extensions                     |     1.9.64 | 118.6 MiB |
| gcloud app Python Extensions                   |     1.9.74 |   6.2 MiB |
| gcloud app Python Extensions (Extra Libraries) |     1.9.74 |  28.5 MiB |
+------------------------------------------------+------------+-----------+
```
as well as the associated "installed" messages, so grpc should be available.

I'm pretty confident this is something in the dev_appserver sandbox because I've tried installing grpcio in the environment and import grpc in the container's python REPL just fine. I've verified that the grpc module is in the cloud_sdk lib folder and I've tried uninstalling and reinstalling the cloud-datastore-emulator component to no effect.

I attempted creating another container that hosted the datastore emulator (which runs fine) and used the environment variable to point dev_appserver over to that container, but the same stack trace results and I get no joy.

So any suggestions would be welcome.

Thanks in advance!

**Comment by cthrax** [comment]
Wow, as soon as I hit send a complete system rebuild worked. Nothing to see here, sorry for the noise.

**Comment by salrashid123** [comment]
i belive the error you're seeing is generic to `dev_appserver.sh` and not this specific docker image.
ref
- [https://issuetracker.google.com/issues/112817362](https://issuetracker.google.com/issues/112817362)
- [https://issuetracker.google.com/issues/111318929](https://issuetracker.google.com/issues/111318929)

**Comment by cthrax** [comment]
I believe the first issue you've linked is what I'm experiencing. I posted here because everything works fine in my host system, but not in the docker container. I'll see if I have anything to add to that other thread, but I think you're right that it's probably not anything the docker image can fix.

**Comment by salrashid123** [comment]
ok; i'm gonna close this out;   feel free to reopen if it turns out specific to the image here
