### ISSUE TITLE
difference between alpine and other images

### ISSUE THREAD

**Issue by rajdhandus** [GoogleCloudPlatform/cloud-sdk-docker#147]
when i try to authenticate to GCP from gcloud container i hit an error with the key format.. this happens only in non-alpine images.. 

gcloud auth activate-service-account --key-file ./gcp.json

+ gcloud auth activate-service-account --key-file ./gcp.json
ERROR: (gcloud.auth.activate-service-account) Could not read json file ./gcp.json: Invalid control character at: line 1 column 175 (char 174)

+ gcloud auth activate-service-account --key-file ./gcp.json
Activated service account credentials for: [terraform-script@xxxx.iam.gserviceaccount.com]

is there a work around.. i think the issue is with how alpine treats the newline characters present in the json file as opposed to debian..

**Comment by salrashid123** [comment]
i don't think its is a bug w/ the sdk image here.  From the error, it looks like the cert file itself is incorrect

- debian
```
$  docker run --rm -ti -v `pwd`:/certs google/cloud-sdk gcloud auth activate-service-account --key-file /certs/service_account.json
Activated service account credentials for: [access-token-creds@mineral-minutia-820.iam.gserviceaccount.com]
```

- alpine
```
$  docker run --rm -ti -v `pwd`:/certs google/cloud-sdk:alpine gcloud auth activate-service-account --key-file /certs/service_account.json
Activated service account credentials for: [access-token-creds@mineral-minutia-820.iam.gserviceaccount.com]

```
