### ISSUE TITLE
Docker image with kubectl included

### ISSUE THREAD

**Issue by tijsg** [GoogleCloudPlatform/cloud-sdk-docker#148]
Could we please have an official dockerfile with the latest version of kubectl included? For now, the only option is to use the cloud SDK image as a base image and use 'gcloud components install kubetl', but it slows down ci/cd pipelines a lot...

**Comment by salrashid123** [comment]
The default `:latest`, `:slim` and labeled version installs `kubectl` at `v1.11.2` (i understand thats the latest version now)

```
$  docker run -ti google/cloud-sdk:214.0.0 kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

---

However, i just noticed the `gcloud components` installer specifies `1.9.7`  [releae notes](https://cloud.google.com/sdk/docs/release-notes#kubernetes_engine_7).  The gcloud-based installer is only used in alpine

```
gcloud components install kubectl

Your current Cloud SDK version is: 214.0.0
Installing components from version: 214.0.0

┌─────────────────────────────────────────────────────────────────────┐
│                 These components will be installed.                 │
├─────────────────────┬────────────────────────┬──────────────────────┤
│         Name        │        Version         │         Size         │
├─────────────────────┼────────────────────────┼──────────────────────┤
│ kubectl             │             2018.08.17 │              < 1 MiB │
│ kubectl             │                  1.9.7 │             14.9 MiB │
└─────────────────────┴────────────────────────┴──────────────────────┘
```

Are you using the base `:alpine` image and the manual component installer?

**Comment by tijsg** [comment]
I am indeed using the alpine image and manual installation. Is there a reason why kubectl is not included in the alpine image?

**Comment by salrashid123** [comment]
the `:alpine` based images intentionally doens't [add on any components](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/alpine/Dockerfile#L13)  at all; just the baseline sdk. 

You can add on `gcloud` components directly or in the case of `kubectl`, independently by extending the base image.

We could create an `:alpine` based image that adds all the components (like `:latest` which is `741 MB`) but that'd be huge and would defeat some of reasons for using alpine.

**Comment by tijsg** [comment]
ok ok it's all clear now, thanks a lot for the information!
