### ISSUE TITLE
Add latest-alpine tag to help with automation

### ISSUE THREAD

**Issue by jgrobbel** [GoogleCloudPlatform/cloud-sdk-docker#150]
In order to pick up the latest version of the alpine images we have automation in place to compare the latest hash to the image we are currently using (used currently with other dockerhub images). But with the current tagging there is no `latest-alpine` that we can compare our current image with.

It would be tremendously useful to us if you could tag the latest alpine image in the same way the base images are tagged.

Thanks

**Comment by salrashid123** [comment]
`:alpine` image itself is should always be the latest sdk in our scheme currently.  Its similar to the other tags in the dockerhub build out there now.

- [https://hub.docker.com/r/google/cloud-sdk/tags/](https://hub.docker.com/r/google/cloud-sdk/tags/)

Currently you've pulled and using `alpine` locally but want to compare it periodicaly to something on dockerhub like `latest-alpine`?   

We don't have `latest-debian` but I'm missing something here, LMK how you'd use the base images instead here in the current scheme (since the same tagging is used for debian based images)

but just FYI, if you needed to go into the container
```
$ docker run -ti google/cloud-sdk:alpine env | grep  CLOUD_SDK_VERSION
CLOUD_SDK_VERSION=217.0.0
```
```
$ docker run -ti google/cloud-sdk:alpine gcloud version --format="value('Google Cloud SDK')"
217.0.0
```

**Comment by jgrobbel** [comment]
@salrashid123 

Thanks for the reply. My use case is that I want to be notified of a new version of a container, but to not automatically pull it down. The reason being that we pin the versions in code and roll them down a pipeline to production. To see if we have the latest version we can look at the `RepoTags`
For example nginx:

```
[neo4j-cloud]$ docker images nginx
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               1.15.3-alpine       994032453556        13 days ago         17.4MB   <<<<
nginx               alpine              994032453556        13 days ago         17.4MB       <<<<
nginx               1.15.2-alpine       36f3464a2197        2 months ago        18.6MB
nginx               1.15.1-alpine       920e5c5c8bed        2 months ago        18.6MB

$ docker inspect nginx:alpine | head -9
[
    {
        "Id": "sha256:994032453556b56420d66d53b7d8db1a74e1193165e2a070e50f533d849d9833",
        "RepoTags": [
            "nginx:1.15.3-alpine",      <<<<Both tags point to the same image
            "nginx:alpine"
        ],
        "RepoDigests": [
            "nginx@sha256:829a63ad2b1389e393e5decf5df25860347d09643c335d1dc3d91d25326d3067"

$ docker inspect nginx:1.15.3-alpine | head -9
[
    {
        "Id": "sha256:994032453556b56420d66d53b7d8db1a74e1193165e2a070e50f533d849d9833",
        "RepoTags": [
            "nginx:1.15.3-alpine",
            "nginx:alpine"
        ],
        "RepoDigests": [
            "nginx@sha256:829a63ad2b1389e393e5decf5df25860347d09643c335d1dc3d91d25326d3067"

$ docker inspect nginx:1.15.2-alpine | head -9
[
    {
        "Id": "sha256:36f3464a21975e5779d081a9e8a78a024c549d1895fc9981d6bd8b67075ebd7b",
        "RepoTags": [
            "nginx:1.15.2-alpine"     <<<< latest has been removed
        ],
        "RepoDigests": [
            "nginx@sha256:23e4dacbc60479fa7f23b3b8e18aad41bd8445706d0538b25ba1d575a6e2410b"
        ],
$
```

But for the google/cloud-sdk images it seems that the actual images are different
```
$ docker images google/cloud-sdk
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
google/cloud-sdk    217.0.0-alpine      eeb3f1d90c81        6 days ago          208MB
google/cloud-sdk    alpine              c84e042f7197        6 days ago          208MB
google/cloud-sdk    206.0.0-alpine      57d4a731615e        3 months ago        180MB


$ docker inspect google/cloud-sdk:217.0.0-alpine | head -9
[
    {
        "Id": "sha256:eeb3f1d90c81b4c2be80af4913713405ccea49ccc146a05b738574dd191cfdba",
        "RepoTags": [
            "google/cloud-sdk:217.0.0-alpine"
        ],
        "RepoDigests": [
            "google/cloud-sdk@sha256:e96a07cd351aedbedd62fbe47b6ed5400dc9efa55b04257d993a2b8e0a182536"
        ],

$ docker inspect google/cloud-sdk:alpine | head -9
[
    {
        "Id": "sha256:c84e042f719793745e833050bda878ca95748f1e6e86256d6216d1bb26f6920a",
        "RepoTags": [
            "google/cloud-sdk:alpine"
        ],
        "RepoDigests": [
            "google/cloud-sdk@sha256:37ac66e6446b48ecbbe734e3a88b340fd711ea0d5baffd751ee70e17dbd350c1"
        ],
```

**Comment by salrashid123** [comment]
ok, thanks for the explanation; i didn't catch the images have different hash alltogether.  I'll try to address that bit vs new image tag.

We're using dockerhub to generate these builds on auto-trigger like this:

![docker_build](https://user-images.githubusercontent.com/11149054/46028725-3587da80-c0a6-11e8-8670-d1de91e0361b.png)

but the same docker images are getting unique hash values for some reason.

---
I'll investigate why this is happening in a bit.   At worst case, we can build+push the images and not depend on dockerhub's trigger-builds.  Or later on just endup using [container-builder](https://cloud.google.com/cloud-build/docs/)  and `gcr.io/google-containers`

**Comment by salrashid123** [comment]
ok, i think this is whats going on: dockerhub automated builds treats each build separately even if the same`Dockerfile` in the same repo is used (dockerhub builds dont' cache layers either).  I also didnt' see anyway in dockerhub automated build system to 'just re-tag` an existing image.

If the images are built outside of dockerhub, tagged and then uploaded, the images are ofcourse the same.

We can abandon the dockerhub builds and instead use GCP [Cloud Build](https://cloud.google.com/cloud-build/docs/) to generate the image.

I setup a __test__ image here and set the following config to trigger builds and the push from GCP (vs allowing dockerhub to build):
- https://gist.github.com/salrashid123/aeacfb4eac2f82651e9f677a90e5d791

eg, this is the _test_ dockerhub repo where i ran the above builder yaml:
  https://hub.docker.com/r/salrashid123/cloud-sdk-docker-test-image/tags/

and as expected:

```
$ docker pull salrashid123/cloud-sdk-docker-test-image:alpine
alpine: Pulling from salrashid123/cloud-sdk-docker-test-image
4fe2ade4980c: Pull complete 
53e0370416c4: Pull complete 
Digest: sha256:676c9c46090919f86e99f473cade898feb9988099fa576989fcdd977bc638f8b
Status: Downloaded newer image for salrashid123/cloud-sdk-docker-test-image:alpine
```
```
$ docker pull salrashid123/cloud-sdk-docker-test-image:218.0.0-alpine
218.0.0-alpine: Pulling from salrashid123/cloud-sdk-docker-test-image
Digest: sha256:676c9c46090919f86e99f473cade898feb9988099fa576989fcdd977bc638f8b
Status: Downloaded newer image for salrashid123/cloud-sdk-docker-test-image:218.0.0-alpine
```

the `RepoTags` are the same:

```
$ docker inspect salrashid123/cloud-sdk-docker-test-image:218.0.0-alpine | head -9
[
    {
        "Id": "sha256:017afad81d0becf636647a4e6aca8d2b363b73fb0be0fe9d0e988d055312349c",
        "RepoTags": [
            "salrashid123/cloud-sdk-docker-test-image:218.0.0-alpine",
            "salrashid123/cloud-sdk-docker-test-image:alpine"
        ],
        "RepoDigests": [
            "salrashid123/cloud-sdk-docker-test-image@sha256:676c9c46090919f86e99f473cade898feb9988099fa576989fcdd977bc638f8b"
```

**Comment by jgrobbel** [comment]
@salrashid123 
Interesting and thanks for investigating. I am not sure why docker hub won't allow multiple tags to the same image (I thought what we were doing was standard practise). Though looks like the nginx folks have a lot of [extra automation and validation](https://github.com/docker-library/repo-info/tree/master/repos/nginx)

If its all the same for you to use GCP Builds over docker then that would be really great 👍

**Comment by cloudsdkdocker** [comment]
We have updated our deployment process to use GCP Builds, this should rectify this issue. I will close this issue for now, please feel free to reopen if you encounter any issues!

**Comment by jgrobbel** [comment]
Great, thank you!
