### ISSUE TITLE
docker static update to 18.09?

### ISSUE THREAD

**Issue by rubensayshi** [GoogleCloudPlatform/cloud-sdk-docker#153]
the docker binary is still coming from 17.12.0 (`FROM docker:17.12.0-ce as static-docker-source`),
is there a reason for not upgrading to 18.09?

**Comment by salrashid123** [comment]
Makes sense to upgrade but i'll defer on this for a bit to accomodate anyone using

```gcloud docker ...``` command set

- https://cloud.google.com/sdk/gcloud/reference/docker
- https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker

Unless its causing issues or the new docker client has some needed capability, might as well keep it at the current docker version until ```gcloud docker ...``` commandset is removed from the SDK.  Once that happens, i see no reason not to upgrade.   We'll keep this open till then.

**Comment by rubensayshi** [comment]
good point, I wanted to give the experimental features (buildkit) a spin but I'll just make my own cloud-sdk image for trying that :)

**Comment by haizaar** [comment]
BUILDKIT + gcr.io private repos = no go. Details: https://github.com/moby/buildkit/issues/720

They guys there says the problem is actually on gcr.io side.
