### ISSUE TITLE
Change image to use non-root user

### ISSUE THREAD

**Issue by ramonmedeiros** [GoogleCloudPlatform/cloud-sdk-docker#154]
I'm using this docker to generate the credentials json and export to other container using volumes--from. The issue is that we are exporting /root, which is not readable from a common user in another container. Let's change this to a common user

**Comment by mlin** [comment]
It's definitely a bummer that gsutil (and perhaps other commands?) seem to have to run as root...

```
$ docker run --rm -it google/cloud-sdk:slim gsutil ls -l gs://hca-dcp-sc-pipelines-test-data/
ERROR: (gsutil) Failed to create the default configuration. Ensure your have the correct permissions on: [/.config/gcloud/configurations].
  Could not create directory [/.config/gcloud/configurations]: Permission denied.

Please verify that you have permissions to write to the parent directory.
```

https://cloud.google.com/solutions/best-practices-for-operating-containers#avoid_running_as_root

**Comment by sarkaramrit2** [comment]
Has anyone figured out a manner one can run 'gsutil' cmds with a non-user?

**Comment by madworx** [comment]
A bit kludgy, but you can achieve it by mounting `/.config` and `/.gsutil` in the container (after having created the corresponding directories on your docker engine host:

```docker run --rm -it --user 1000 -v $(pwd)/csdkconfig/:/.config -v $(pwd)/csdgsutil:/.gsutil -w /.config google/cloud-sdk:slim gsutil ls -l gs://hca-dcp-sc-pipelines-test-data/```

**Comment by sarkaramrit2** [comment]
Thanks @madworx . appreciate it.

**Comment by benbuzbee** [comment]
I would submit a PR but I notice none of the simple PRs have been looked at since January :(

But the fix is simple, just set HOME to /tmp so gsutil can write to  it as any user
```
-e HOME=/tmp
```

**Comment by number33** [comment]
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/213 was reverted, should this issue be re-opened for now?
