### ISSUE TITLE
Feature request: add the helm binary

### ISSUE THREAD

**Issue by danacr** [GoogleCloudPlatform/cloud-sdk-docker#157]
I am using this image for CI/CD purposes and noticed that it would be beneficial to have helm out of the box.

Since the image already provides kubectl, would this addition be useful for others as well?

**Comment by cloudsdkdocker** [comment]
Hi Danacr,

We currently do not plan to add helm to the Docker Image as we haven't seen the demand we would want in order to add it. If we see an increase in interest in this we will reconsider, but for now I'm closing this issue.

**Comment by bagratte** [comment]
@cloudsdkdocker How are you monitoring the demand for helm? I would also like to see helm out of the box.

**Comment by Dentrax** [comment]
Any updates about providing a Helm Chart?
