### ISSUE TITLE
240.0.0 broke datastore emulator

### ISSUE THREAD

**Issue by gannett-ggreer** [GoogleCloudPlatform/cloud-sdk-docker#159]
"ERROR: (gcloud.beta.emulators.datastore.start) To use the Google Cloud Datastore emulator, a Java 8+ JRE must be installed and on your system PATH"

I suspect `apt-get` was pulling in a dependency you didn't realize when switching to the `tar` install.

**Comment by salrashid123** [comment]
Sorry about that;  we shifted over from using the `apt-` based installer to the `.tar.gz` to get more coverage on the components that are installed.
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/158
However, as you noted, the emulator has a dependency which isn't called out while listing the installed components via `gcloud`  (it should call it out)

Anyway, we'll revert back to and reassess the dependencies needed to move off of the `apt-installer`

**Comment by salrashid123** [comment]
ok, we updated the dockerhub repo for all the sdk flavors that were impacted

```
$ docker run -ti google/cloud-sdk /bin/bash
Unable to find image 'google/cloud-sdk:latest' locally
latest: Pulling from google/cloud-sdk
741437d97401: Pull complete 
43591ec5a587: Pull complete 
4ba560186142: Pull complete 
Digest: sha256:f0998019828ab81a9b48978ba213f827948557cf51d9bf66ea2a7255b68ed5b0
Status: Downloaded newer image for google/cloud-sdk:latest

root@4bbb074f5dbe:/# gcloud config set project foo
Updated property [core/project].

root@4bbb074f5dbe:/# gcloud version
Google Cloud SDK 240.0.0
alpha 2019.03.22
app-engine-go 
app-engine-java 1.9.72
app-engine-python 1.9.84
app-engine-python-extras 1.9.84
beta 2019.03.22
bigtable 
bq 2.0.42
cbt 
cloud-datastore-emulator 2.1.0
core 2019.03.22
datalab 20190116
gsutil 4.37
kubectl 2019.03.22
pubsub-emulator 2019.03.22
root@4bbb074f5dbe:/# gcloud beta emulators datastore start
Executing: /usr/lib/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator create --project_id=foo /root/.config/gcloud/emulators/datastore
[datastore] Mar 26, 2019 11:40:24 PM com.google.cloud.datastore.emulator.CloudDatastore$CreateAction$1 apply

```
