### ISSUE TITLE
Python and Java GAE apps access the same local dev server datastore

### ISSUE THREAD

**Issue by espeed** [GoogleCloudPlatform/cloud-sdk-docker#16]
Does the latest Google Cloud SDK enable Python and Java GAE apps to access the same local dev server and datastore?

Earlier this year @proppy said, "gcd.sh wraps the Java App Engine development server, so you can't currently share data between an App Engine Python development environment and a Cloud Datastore development environment: see #21."
- https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/31
- https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/21

Yesterday I asked about this in the #google-containers IRC channel, and ~isdal chimed in to say this is now possible -- "The new gcloud SDK allows you to run multiple docker containers at the same time with all of them sharing the same datastore (and other APIs)."

If so, what dev server do you run and how do you configure the Docker apps?

**Comment by salrashid123** [comment]
Closing out old issues/comments; its not really about the docker image here.
