### ISSUE TITLE
240.0.0 does not fall back to default zone and region in local client? 

### ISSUE THREAD

**Issue by carolfly86** [GoogleCloudPlatform/cloud-sdk-docker#160]
The new 240.0.0 does not fall back to default zone and region set in local client? I tested it works fine 239.0.0 

```
+ gcloud config get-value compute/zone
us-west1-a
+ gcloud compute disks create xxx-disk --size 1500GB --type pd-ssd
ERROR: (gcloud.compute.disks.create) Underspecified resource [xxx-disk]. Specify one of the [--region, --zone] flags.
```

**Comment by salrashid123** [comment]
@carolfly86   Can you confirm if the behavior you saw was while running within the `google/cloud-sdk` docker image or just generally with `gcloud` outside of that image?   (the former is what the current repo represents).

**Comment by carolfly86** [comment]
@salrashid123 it's generally with gcloud outside of the image.

**Comment by carolfly86** [comment]
Please close the issue . I have opened an issue with cloud sdk https://issuetracker.google.com/issues/129362599
