### ISSUE TITLE
gcloud emulators firestore default data-dir

### ISSUE THREAD

**Issue by privet56** [GoogleCloudPlatform/cloud-sdk-docker#161]
In the running docker container calling
`$ gcloud beta emulators firestore start`
i would like to specify the **directory** where firestore saves its data
(and map this directory in the `docker run -v ...` command).
Is there such a ~`--data-dir=` switch available for the firestore command, or
where is firestore saving its data by default?
(**/opt/data/** is empty after a `docRef.set(data).get();` call)

**Comment by cloudsdkdocker** [comment]
Hi Privet56, I would recommend directing this question to the Cloud SDK Public Issue Tracker as it is related to gcloud functioning more broadly. https://b.corp.google.com/issues/new?component=187143&template=800102
