### ISSUE TITLE
Breaks 64bit library

### ISSUE THREAD

**Issue by dorg-smartin** [GoogleCloudPlatform/cloud-sdk-docker#168]
The dockerfile has it symlinking over the /lib64 directory "ln -s /lib /lib64 &". 
This, in general, should NEVER be done on any OS.An example of how this literally breaks the OS in this case. You can see in the dockerfile they install "libc6-compat" with the following

"RUN apk --no-cache add \curl \python \py-crcmod \bash \libc6-compat \openssh-client \git \gnupg \"

Notice also the alpine version is 3.9 based on "FROM alpine:3.9".In alpine 3.9 the libc6-compat installs the library in /lib64/ld-linux-x86-64.so.2 (https://pkgs.alpinelinux.org/contents?branch=v3.9&name=libc6-compat&arch=x86_64&repo=main) since you then symlink lib over lib64 the library cannot be found.

Note: In alpine 3.8 libc6-compat installed to /lib/ld-linux-x86-64.so.2 (https://pkgs.alpinelinux.org/contents?branch=v3.8&name=libc6-compat&arch=x86_64&repo=main) so the symlink would not have broken this library. 

Regardless though the symlink is very bad practice on any linux OS.

**Comment by dorg-smartin** [comment]
This is for the alpine

**Comment by cloudsdkdocker** [comment]
Hi dorg-smartin. Apologies for the delay in our response, the cloudsdk team has been working to fully integrate the release of these images into our release workflow. We will modify the alpine image to prevent this breakage here in the very near future.

**Comment by cloudsdkdocker** [comment]
Issue was fixed in release 253.0.0 https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/6828ccb495dfd210d8520a5463fc39f0a3d79e57#diff-4d70762b86e15b8a63ed6fad0d8bb891
