### ISSUE TITLE
Python3 in alpine

### ISSUE THREAD

**Issue by samanvp** [GoogleCloudPlatform/cloud-sdk-docker#170]
Currently alpine has only one version of python (Python 2.7.16). I am wondering if there is any plan to also add Python 3?

Thanks!

**Comment by cloudsdkdocker** [comment]
Hi Samanvp,

We are currently working to update the entirety of the Cloud SDK codebase to be python 3 compatible, at which point we will update the image to use python 3. Until then the image will likely keep only 2.7.16.

**Comment by dinvlad** [comment]
An email from Google informed us that SDK 274.0.0 (which is now included in these images) supports 3.5+. Non-Alpine images already ship with Python 3.7. Are there plans to transition this image to 3.7 as well? Thanks!

**Comment by vilasj** [comment]
While 274.0.0 announced GA support for Python 3.5+, we have not yet switched the default Python interpreter used in our various release channels to Python 3.5+. We plan to do that after monitoring feedback from our users for at least a few weeks. In the meantime, you can run [gcloud topics startup](https://cloud.google.com/sdk/gcloud/reference/topic/startup) to see how you can control the Python interpreter used during execution of various SDK binaries.
