### ISSUE TITLE
Updating from 229 to 252 breaks pubsub publishing

### ISSUE THREAD

**Issue by ThomWright** [GoogleCloudPlatform/cloud-sdk-docker#171]
```diff
-FROM google/cloud-sdk:229.0.0-alpine
+FROM google/cloud-sdk:252.0.0-alpine
```

We have a bunch of tests which use the pubsub emulator. Updating the version of the Docker image (as above) breaks our tests.

On 229, we could successfully publish messages to a topic, and receive them on subscriptions. Now, any messages that get published get lost in the void and no subscription ever receives them.

We're using `@google-cloud/pubsub@0.28.1` from NPM.

I haven't managed to find any more debugging info. Let me know if there's anything else you need.

**Comment by willfaris** [comment]
Is this still an issue? Can you show the error if it is?

**Comment by willfaris** [comment]
Please re-open if this is still an issue.
