### ISSUE TITLE
Any concerns about updating base Docker version?

### ISSUE THREAD

**Issue by inductor** [GoogleCloudPlatform/cloud-sdk-docker#178]
It seems that you're using Docker 17.12 for the base image. Now that 19.03 is out and 17.x is surely getting to be deprecated and I guess it should be updated.

I'm wondering if there's any reasons why you can't update it. Is there?

**Comment by cloudsdkdocker** [comment]
We're currently reluctant to update past 17.12 as it breaks `gcloud docker` commands, however given how outdated this is starting to become it might soon be time to consider it.

Fore reference: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/153

**Comment by willfaris** [comment]
19.03.11 is now being used in all images.
