### ISSUE TITLE
"credential_file_override" is not working properly

### ISSUE THREAD

**Issue by derekhh** [GoogleCloudPlatform/cloud-sdk-docker#179]
Based on what's stated in the [Usage](https://github.com/GoogleCloudPlatform/cloud-sdk-docker#usage) section, I'm trying to override the credential file via:

```
docker run -e CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/tmp/user-gcp-sa.json -v /tmp:/tmp google/cloud-sdk:latest sh -c "ls /tmp/user* && echo "" && gcloud config list && gcloud auth list"
```

The output of the above command is shown below:

```
/tmp/user-gcp-sa.json

[auth]
credential_file_override = /tmp/user-gcp-sa.json
[core]
disable_usage_reporting = True

Your active configuration is: [default]

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
```

This means setting up the environment variable `CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE` could correctly override `gcloud config` but it still is not enough to get authenticated successfully.

The following command shows the JSON file is a valid service account key file:

```
docker run -v /tmp:/tmp google/cloud-sdk:latest sh -c "gcloud auth activate-service-account --key-file=/tmp/user-gcp-sa.json && gcloud auth list"
```

The output of the above command is:

```
Activated service account credentials for: [foo@bar.iam.gserviceaccount.com]

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

                         Credentialed Accounts
ACTIVE  ACCOUNT
*       foo@bar.iam.gserviceaccount.com
```

**Comment by sebglon** [comment]
Hi,
Have you found a solution? Or a workaround?

**Comment by jameslynnwu** [comment]
`gcloud auth list` does not take the `auth/credential_file_override` into account when displaying accounts.

Any other command that you execute should use the correct account from `auth/credential_file_override`.

**Comment by willfaris** [comment]
I can confirm that `gcloud auth list` does NOT show  the effect of `auth/credential_file_override` but other commands do use the identity stored in the file pointed to by `auth/credential_file_override`

**Comment by JacobHayes** [comment]
Any chance this could be fixed (I may be able to help out, with some pointers)? It makes debugging workflows using an override much more complicated.
