### ISSUE TITLE
Docker is old

### ISSUE THREAD

**Issue by dorg-smartin** [GoogleCloudPlatform/cloud-sdk-docker#181]
Please update the from to a docker 19 version, the version you are using was released in 2017 and does not have docker buildpack support which is crucial for modern dockerfiles.

**Comment by siamsot** [comment]
This is answered also in #178 and #153 as well. At the moment it's not possible due to some blocking issues

**Comment by dorg-smartin** [comment]
The issue is with google SDK supported by google, correct?

**Comment by willfaris** [comment]
19.03.11 used in all images now.
