### ISSUE TITLE
Installing google-cloud-sdk-datastore-emulator on 271 slim fails with openjdk-8-jdk not installable

### ISSUE THREAD

**Issue by ulsa** [GoogleCloudPlatform/cloud-sdk-docker#184]
Installing google-cloud-sdk-datastore-emulator on 271 slim fails with:

```
 google-cloud-sdk-datastore-emulator : Depends: openjdk-8-jdk but it is not installable
```

I've followed the instructions on https://hub.docker.com/r/google/cloud-sdk under "Installing additional components":

```
cd debian_slim/
docker build --build-arg CLOUD_SDK_VERSION=271.0.0 \
    --build-arg INSTALL_COMPONENTS="google-cloud-sdk-datastore-emulator" \
    -t my-cloud-sdk-docker:slim .
```

Docker Desktop Mac
Docker version 19.03.4, build 9013bf5

**Comment by LiuVII** [comment]
would be nice to have an answer for this, still happening in all newer versions as well

**Comment by willfaris** [comment]
Waiting for datastore emulator to declare support for Java 11.  If you need the emulator in an image on dockerhub you will have to use the tag `google/cloud-sdk:latest` which has the emulator installed already but is much larger than slim.

**Comment by willfaris** [comment]
Starting in Cloud SDK 311.0.0 (expected release date 9/22) the deb package google-cloud-sdk-datastore-emulator will no longer require "openjdk-8", it will require openjdk-8-jdk | openjdk-11-jdk.

**Comment by willfaris** [comment]
This is still not working, google-cloud-sdk-datastore-emulator works with openjdk-11-jdk now but openjdk-11-jdk will not install on debian:buster-slim, the below build fails.

FROM docker:19.03.11 as static-docker-source

FROM debian:buster-slim
RUN apt-get update -qqy && apt-get install -qqy openjdk-11-jdk

**Comment by willfaris** [comment]
Looks related to

https://github.com/geerlingguy/ansible-role-java/issues/64

**Comment by willfaris** [comment]
docker build --build-arg CLOUD_SDK_VERSION=311.0.0  --build-arg INSTALL_COMPONENTS="google-cloud-sdk-datastore-emulator" -t my-cloud-sdk-docker:slim .

Is now working.
