### ISSUE TITLE
Debian slim is not based on debian-slim image

### ISSUE THREAD

**Issue by inductor** [GoogleCloudPlatform/cloud-sdk-docker#190]
Hi,

The base image for `gcloud:slim` is not based on Debian slim image, which is a little bit confusing for the naming. It is just buster but not buster-slim.

https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/debian_slim/Dockerfile#L3

I tried to create images based on both `debian:buster` and `debian:buster-slim`, and it seems that `buster-slim` is 100MB lighter than `buster`.

I wonder if there's any reasons why you don't use the slim base image.

```
$ docker images
REPOSITORY          TAG                            IMAGE ID            CREATED              SIZE
slim                latest                         10ec50a8c752        7 seconds ago        813MB
nonslim             latest                         64af3dba8272        About a minute ago   924MB
```

Thanks,

**Comment by willfaris** [comment]
debian-slim now uses debian:buster-slim
