### ISSUE TITLE
where is repo 'docker:'?

### ISSUE THREAD

**Issue by bimargulies-google** [GoogleCloudPlatform/cloud-sdk-docker#198]
When I attempt to build (e.g.) the Alpine image for myself, the FROM from docker: fails as unknown or inaccessible. Could the README.md please explain what needs to be true for this to succeed?

**Comment by s4shyam95** [comment]
Can you provide the entire error that you got when trying to build the alpine image ?

**Comment by willfaris** [comment]
Can not repro.
