### ISSUE TITLE
Provide alpine images for emulators

### ISSUE THREAD

**Issue by eddumelendez** [GoogleCloudPlatform/cloud-sdk-docker#202]
Currently using [testcontainers](https://github.com/testcontainers/testcontainers-java)  to spin up emulators such as `datastore`, `firestore`, `pubsub`. In order to reduce the size of the images I am using the `alpine` image but need additional steps to install the components already mentioned. I think it would be awesome to get these components already installed in independent images with the `cloud sdk`.

Images can be:

* `google/cloud-sdk-datastore-emulator`
* `google/cloud-sdk-firestore-emulator`
* `google/cloud-sdk-pubsub-emulator`

**Comment by willfaris** [comment]
Currently the buster-slim image fails to install openjdk 8 which is a requirement for the emulators so we would have to use the buster image which would be ~ the same size as the default image which already has the three emulators installed. When the emulators certify that openjdk 11 can be used and the deb packages are updated we could build images for each emulator using buster-slim.

**Comment by eddumelendez** [comment]
@willfaris thank you so much for the update. I will look forward for this.

**Comment by joergi** [comment]
@willfaris does this help? 
https://github.com/docker-library/openjdk/blob/89851f0abc3a83cfad5248102f379d6a0bd3951a/8-jdk/Dockerfile

**Comment by willfaris** [comment]
That example does not look buster related?  I tried briefly to install openjdk8 from sid repo and it failed using buster-slim (does work with buster). I don't think we would officially release that solution tbh because I think the solution would be brittle.  We are pushing to be able to use java 11 soon.

**Comment by joergi** [comment]
allright.
and yeah, it's not working, because it's not supported anymore in buster.... just openjdk 11

I just found this solution too: https://github.com/logbee/docker-java/blob/master/openjdk-8-jre-slim-buster/Dockerfile
but I agree, to use the official way...

**Comment by willfaris** [comment]
Still waiting for all emulator components to declare support for Java 11.

**Comment by willfaris** [comment]
So all emulators work with Java 11 now, I tried out alpine but the bigtable emulator will not work with the alpine c library, it really wants a full glibc, might have to go with debian_slim for now.

**Comment by willfaris** [comment]
Release 316.0.0 should build and publish the new emulators image, looks to be around 700MB, If we can figure out how to use alpine and the bigtable emulator it would go down to ~ 400mb. Release 316.0.0 is scheduled to go live October 27th, 2020,

**Comment by eddumelendez** [comment]
thanks @willfaris ! that's big news :)

**Comment by willfaris** [comment]
So the emulator image is up. There is one image not 3 but it has bigtable,datastore,firestore,pubsub,spanner emulators.  Its not tiny but its not huge, if I can figure out how to get glibc on alpine safely and consistently the image can be made even smaller.  The spanner emulator requires glibc.

Example usage

```docker run google/cloud-sdk:emulators bash -c "gcloud beta emulators bigtable start"```
