### ISSUE TITLE
arm64 image needed

### ISSUE THREAD

**Issue by wangxiyuan** [GoogleCloudPlatform/cloud-sdk-docker#204]
Hi, community
    We met a case that we need to use google cloud-sdk docker image on aarch64 machine. But there is no official arm64 version image. Is it possible that the community can build one to dockerhub?

Thanks.

**Comment by jingxu97** [comment]
Also is there a image available for windows? Or is there a plan to support for windows? Thanks!

**Comment by willfaris** [comment]
There are no current plans for a windows image.

**Comment by willfaris** [comment]
There are no current plans to make an arm64 image.

**Comment by willfaris** [comment]
Windows installer is here

https://cloud.google.com/sdk/docs/downloads-interactive#windows

**Comment by darkedges** [comment]
Shame. I need this for jenkins x.

built my own version
```
[root@instance-20211211-1634 debian_slim]# uname -a
Linux instance-20211211-1634 5.4.17-2102.206.1.el7uek.aarch64 #2 SMP Wed Oct 6 16:38:40 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
[root@instance-20211211-1634 debian_slim]# docker run -ti  google/cloud-sdk:slim gcloud version
Google Cloud SDK 367.0.0
alpha 2021.12.10
beta 2021.12.10
bq 2.0.72
core 2021.12.10
gsutil 5.5

```

**Comment by edwmurph** [comment]
<details>
<summary>this dockerfile worked for my use case running custom gcloud scripts on a rasp pi 4</summary>

```
# python 3.9.10 arm64 https://hub.docker.com/layers/python/library/python/3.9.10/images/sha256-c612029f22fa1985db24dbcd4aba2abdbdc0f822887b96d2d2ae7d30b2d6cd4b?context=explore
FROM python@sha256:c612029f22fa1985db24dbcd4aba2abdbdc0f822887b96d2d2ae7d30b2d6cd4b

RUN apt update

RUN apt -y upgrade

RUN apt install -y curl

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

WORKDIR /app

COPY . .

RUN gcloud version

CMD ["echo", "hi"]
```
</details>

**Comment by maelvls** [comment]
I think the DockerHub images (`google/cloud-sdk`) have been deprecated. They only provide you with amd64 images.

Reading in the [official documentation](https://cloud.google.com/sdk/docs/downloads-docker), it seems like the official images (including amd64 and arm64 variants) are available at `gcr.io/google.com/cloudsdktool/google-cloud-cli`. For example:

```sh
docker pull gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
```

**Comment by cloudsdkdocker** [comment]
You are correct ^ . ARM images have been released for all images other than the default/:latest image and are hosted on GCR. The :latest image has some installed components that do not support ARM so it's not possible currently to create an ARM version of it.

**Comment by paolomainardi** [comment]
Hi everyone, just tried to use it on Apple Silicon:

```shell
➜  ~ docker run --rm gcr.io/google.com/cloudsdktool/google-cloud-cli:410.0.0 arch
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
x86_64
```

Am i doing something wrong ?

Altro tried to inspect the manifest, no luck:

```shell
➜  ~ docker manifest inspect gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
Get "https://gcr.io/v2/google.com/cloudsdktool/google-cloud-cli/manifests/latest": denied: Token exchange failed for project 'google.com:cloudsdktool'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```

**Comment by paolomainardi** [comment]
Ok found, just the alpine and debian are arm supported:

```
➜  ~ docker run --rm gcr.io/google.com/cloudsdktool/google-cloud-cli:410.0.0-alpine arch
Unable to find image 'gcr.io/google.com/cloudsdktool/google-cloud-cli:410.0.0-alpine' locally
410.0.0-alpine: Pulling from google.com/cloudsdktool/google-cloud-cli
47517142f6ba: Already exists
d7dad65d722f: Pull complete
f88833b0317d: Pull complete
1fc3a61200d6: Pull complete
ae4c1f4b6151: Pull complete
504145f94b6c: Pull complete
Digest: sha256:07ccb1c3591c56ebe107d9fa874f5b56961a90ae5f47d98c0d651c7be3a7057d
Status: Downloaded newer image for gcr.io/google.com/cloudsdktool/google-cloud-cli:410.0.0-alpine
aarch64
```

Thanks!
