### ISSUE TITLE
Cannot set project ID inside a script

### ISSUE THREAD

**Issue by quentinalbertone** [GoogleCloudPlatform/cloud-sdk-docker#205]
Hello,

I'm trying to create a github actions which will make a `gcloud container clusters get-credentials`.
In order to create this action I run a script within a docker
* Dockerfile
```Bash
FROM google/cloud-sdk:290.0.0 # use the biggest image for test

COPY entrypoint.sh /entrypoint.sh

RUN apt-get install -qqy jq

ENTRYPOINT ["/entrypoint.sh"]
```
* `entrypoint.sh`
``` Bash
#!/bin/bash
base64 --decode <<< $1 > gcloud-service-key.json # Where $1 is my base64 service account json key
project=$(cat gcloud-service-key.json | jq '.project_id')
account=$(cat gcloud-service-key.json | jq '.client_email')
echo -e "=> project: $project"
echo -e "=> account: $account"
gcloud auth activate-service-account $account --key-file=./gcloud-service-key.json --project=$project
...
```
And I got this error
```
ERROR: (gcloud) The project property must be set to a valid project ID, not the project name ["helium-XXXX"] # The project id
To set your project, run:

  $ gcloud config set project PROJECT_ID

or to unset it, run:

  $ gcloud config unset project
```
(I tried the `config set project` in fact every time I mentioned the project Id, I got the same error)
Could you tell me why this issue append ? or maybe I did it the wrong way

Thanks

**Comment by gerbercj** [comment]
When you open the dashboard at https://console.cloud.google.com/home/dashboard, you should see a "Project info" card displayed. It should include a "Project name", "Project ID", and "Project number". You want to provide the second value, but it sounds like you are providing the first.

**Comment by quentinalbertone** [comment]
Thanks for your answer but I'm providing the right value
by using the field `project_id` in the service account json key gave by GCP, which is the same as the `ProjectID` on the gcloud console

**Comment by quentinalbertone** [comment]
I think that I found the solution, thanks @gerbercj `jq` add double quotes. I made a lot of change but now with `project=$(cat gcloud-service-key.json | jq -r '.project_id')` , among other things, it works !

**Comment by rv1448** [comment]
Thank you @quentinalbertone. I had same issue using jq -r helped.
