### ISSUE TITLE
Google Cloud Platform functional tests

### ISSUE THREAD

**Issue by paualarco** [GoogleCloudPlatform/cloud-sdk-docker#207]
Hello!

As in the documentation is indicated, this image dokerizes all `gcloud` services, but what ports should be mapped and exposed in order to make them available? (This is not mentioned in the documentation)

In my particular case I would just need the `Google Cloud Storage` service.

**Comment by cloudsdkdocker** [comment]
Hi Pau,

This image exists specifically to provide a docker image with the Cloud SDK pre-installed on it to be used as needed within the container. No work has been done to expose the installation via ports.
