### ISSUE TITLE
README Badges 404

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/cloud-sdk-docker#211]
The badges in the README.md 404.

Repro:

Click the links after:
"Check out Container Registry for available tags:"

Observe they are broken as they link to this page:
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master

**Comment by willfaris** [comment]
But they look nice.

**Comment by grant** [comment]
If you want to keep the images, can we remove the links from them?

They still 404.

**Comment by grant** [comment]
@willfaris please re-open this issue.
