### ISSUE TITLE
appctl support

### ISSUE THREAD

**Issue by kylepw** [GoogleCloudPlatform/cloud-sdk-docker#212]
I was wondering if support of the GCP _Application Delivery_ command `appctl `will be available in a future cloud-sdk-docker image to provide better integration with Cloud Build?

**Comment by willfaris** [comment]
appctl is not packaged as a deb package so it is not possible to add it to most of our images, however I will add appctl to the `google/cloud-sdk:debian_component_based` image starting with release 310.0.0.

**Comment by willfaris** [comment]
'google/cloud-sdk:310.0.0-debian_component_based' should have appctl installed by default. It is scheduled to be released on 20200915.
