### ISSUE TITLE
Can no longer install packages

### ISSUE THREAD

**Issue by ababkov** [GoogleCloudPlatform/cloud-sdk-docker#214]
Using alpine:latest, scripts using `apk add` no longer work.

`apk add curl` - Worked on images prior to 304.0.0.

Now receiving the following error:

```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

I'm guessing it's related to this commit: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/96834d070e47c7a56c32dc1ce64e86083eebf709

Would be good to understand if this is intended behaviour / an intended change or a regression.

**Comment by patrickmcgraw** [comment]
I think this is also related to an issue I'm seeing in cloudbuild using a build step like:

    - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
      entrypoint: gcloud
      id: configured
      args:
      - 'config'
      - 'set'
      - 'app/cloud_build_timeout'
      - '3000s'

It results in an error message like:

    BUILD
    Starting Step #0 - "configured"
    Step #0 - "configured": Pulling image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    Step #0 - "configured": alpine: Pulling from google.com/cloudsdktool/cloud-sdk
    Step #0 - "configured": cbdbe7a5bc2a: Already exists
    Step #0 - "configured": 6e00981b9060: Pulling fs layer
    Step #0 - "configured": 1b42e8b6fcb3: Pulling fs layer
    Step #0 - "configured": 995add225b99: Pulling fs layer
    Step #0 - "configured": 2dadf6e2c33a: Pulling fs layer
    Step #0 - "configured": 2dadf6e2c33a: Waiting
    Step #0 - "configured": 1b42e8b6fcb3: Verifying Checksum
    Step #0 - "configured": 1b42e8b6fcb3: Download complete
    Step #0 - "configured": 2dadf6e2c33a: Verifying Checksum
    Step #0 - "configured": 2dadf6e2c33a: Download complete
    Step #0 - "configured": 6e00981b9060: Verifying Checksum
    Step #0 - "configured": 6e00981b9060: Download complete
    Step #0 - "configured": 995add225b99: Verifying Checksum
    Step #0 - "configured": 995add225b99: Download complete
    Step #0 - "configured": 6e00981b9060: Pull complete
    Step #0 - "configured": 1b42e8b6fcb3: Pull complete
    Step #0 - "configured": 995add225b99: Pull complete
    Step #0 - "configured": 2dadf6e2c33a: Pull complete
    Step #0 - "configured": Digest: sha256:a53293944e9ace21f3b0d7c22e5e6b41b41016b154e9632e218e5407cb43150f
    Step #0 - "configured": Status: Downloaded newer image for gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    Step #0 - "configured": gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    Step #0 - "configured": WARNING: Could not setup log file in /builder/home/.config/gcloud/logs, (Error: Could not create     directory [/builder/home/.config/gcloud/logs/2020.08.04]: Permission denied.
    Step #0 - "configured": 
    Step #0 - "configured": Please verify that you have permissions to write to the parent directory.)
    Step #0 - "configured": ERROR: (gcloud.config.set) Failed to create the default configuration. Ensure your have the correct     permissions on: [/builder/home/.config/gcloud/configurations].
    Step #0 - "configured":   Could not create directory [/builder/home/.config/gcloud/configurations]: Permission denied.
    Step #0 - "configured": 
    Step #0 - "configured": Please verify that you have permissions to write to the parent directory.

**Comment by baublet** [comment]
In our case it was related to [this commit](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/96834d070e47c7a56c32dc1ce64e86083eebf709#diff-3254677a7917c6c01f55212f86c57fbf) and recent update to the Docker image. The image no longer uses the root user, but a new one (`cloudsdk`).

To fix this, we needed to switch our Circle CI configuration to use root:

```
  build-docker:
    docker:
      - image: google/cloud-sdk
        user: root   # <-- This is new, and fixed the image
```

YMMV

**Comment by gerbercj** [comment]
I have just reverted the commit. I will try testing this locally, but would also appreciate hearing if this addresses the issue for @ababkov and @patrickmcgraw .

**Comment by allanlw** [comment]
@gerbercj Is there an ETA on when the revert will be live on gcr.io? This broke my build with the following step:
```
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ["app", "deploy", "app.yaml", "cron.yaml", "-v", "prod", "--stop-previous-version", "--promote"]
```

**Comment by patrickmcgraw** [comment]
@gerbercj  Will the version number of the image change at https://console.cloud.google.com/gcr/images/google.com:cloudsdktool/GLOBAL/cloud-sdk?gcrImageListsize=30 due to the rollback?

I can confirm that manually pinning our version to `303.0.0-alpine` did work. But rolling it back to `alpine` latest just now still did not work.

**Comment by gzeskas** [comment]
The same issue with `slim` version,
Couldn't install additional packages on top with apt getting error:

`Step 1/3 : FROM google/cloud-sdk:slim
 ---> 6f2ad1762d73
Step 2/3 : RUN apt-get update && apt-get install -y bash
 ---> Running in 1708bfe0d002
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/`

**Comment by miguelsimon** [comment]
This broke some of our builds as well, changing the user to non-root is likely to cause problems for quite a few people.

Reverting the `gcr.io/google.com/cloudsdktool/cloud-sdk` image might be a good idea.

**Comment by thecodeassassin** [comment]
Any idea how I can make it work on cloud build? How do I run steps as root? All our builds are failing now.

**Comment by patrickmcgraw** [comment]
@gerbercj The `9cd1269717bc` revision of `304.0.0-alpine` is working in our build now.

**Comment by miguelsimon** [comment]
@gerbercj, I've observed the following, pulling from `google/cloud-sdk:latest`:

* about 30 minutes ago, the `sha256:dca800e43a50972e4de6e32f2cded14f1feeee2bdc9dd630d7f0514881c7657d` revision made things depending on root work again
* a subsequent update about 15 minutes ago, to `sha256:4df3c4e46642e80fdb7963c4cdbb816bc6f9f2be4b71b7b29517a89d953f04e9` broke things again.

**Comment by gerbercj** [comment]
I've just finished pushing updated images to Dockerhub and gcr.io. This includes updating the 'latest' tag to include the new commits.

**Comment by thecodeassassin** [comment]
@gerbercj will this change back later? I cannot find how to run a cloud build step as root. We need to install custom packages such as jq.

**Comment by alexrohv** [comment]
@gerbercj We just ran the [latest](https://console.cloud.google.com/gcr/images/google.com:cloudsdktool/GLOBAL/cloud-sdk@sha256:4df3c4e46642e80fdb7963c4cdbb816bc6f9f2be4b71b7b29517a89d953f04e9/details?tab=info) tag but saw the same permission issue.

**Comment by sww314** [comment]
We are seeing the same issue on Cloud Build with the latest tag. 
```
Digest: sha256:4df3c4e46642e80fdb7963c4cdbb816bc6f9f2be4b71b7b29517a89d953f04e9
Status: Downloaded newer image for gcr.io/google.com/cloudsdktool/cloud-sdk:latest
gcr.io/google.com/cloudsdktool/cloud-sdk:latest
```

**Comment by gerbercj** [comment]
Thanks for the updates everyone. I'm looking at the updated images now to see why they would be missing the rollback. Once we sort this out the expected state is that the containers are running as root, as they were before commit 96834d0.

**Comment by gerbercj** [comment]
I've just finished running our standard Cloud Build pipeline to regenerate the gcr.io images in the same manner as a standard deployment process. I then pulled the each container and ran `whoami` in it, all of which returned `root`.

**Comment by miguelsimon** [comment]
Seeing the expected behaviour on the dockerhub `google/cloud-sdk` image revision `72ce62fcbefb`, thanks @gerbercj.

**Comment by loozhengyuan** [comment]
Sorry everyone for inconvenience today, this was on me, should have tested it more extensively before submitting the change. Glad that it was reverted quickly, thanks @gerbercj.

**Comment by ababkov** [comment]
Thanks all for participating and @gerbercj for actioning the fix ❤️ Can confirm issue the issue posted is resolved.
