### ISSUE TITLE
[Feature Request] Provide an image that offers kubectl installed as gcloud component

### ISSUE THREAD

**Issue by sstncr** [GoogleCloudPlatform/cloud-sdk-docker#219]
Hi,

Currently the kubectl version installed in the docker image is not the same as the version you get if install it as a gcloud component. As of today gcloud installs by default 1.16 and the latest docker image offers 1.19.
This is annoying for developers who install it as gcloud components because differences between versions.
Also, the version from gcloud is usually in sync with the stable version in GKE.

Obviously you can manually install a version in the docker image (but this is annyoing in CI environments as it takes time) or use a fixed tag, but it would be nice if you could offer a docker tag that comes with kubectl installed as a gcloud component.

**Comment by sstncr** [comment]
Ok, never mind I just see debian_component_based exists - though the this page https://hub.docker.com/r/google/cloud-sdk/ doesn't mention it.
Thanks!

**Comment by willfaris** [comment]
https://hub.docker.com/r/google/cloud-sdk/ now calls out 'google/cloud-sdk:debian_component_based' tag
