### ISSUE TITLE
Alpine image over 500Mb in size.

### ISSUE THREAD

**Issue by abhijithshivaswamy** [GoogleCloudPlatform/cloud-sdk-docker#221]
Hi, the alpine image version is over 500Mib in size, and the slim is around a Gib in size, it is me or this is too much for a command line tool/sdk?

```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
google/cloud-sdk        latest              9ef9d0d83c05        42 hours ago        2.23GB
google/cloud-sdk        slim                1887c17c60ca        42 hours ago        1.07GB
google/cloud-sdk        alpine              f7a6ee73b832        42 hours ago        548MB
```

**Comment by willfaris** [comment]
The alpine image is as big as it is because it includes so many components and their deps, aka a full JRE etc, see the installed components list.

**Comment by lrishi** [comment]
> The alpine image is as big as it is because it includes so many components and their deps, aka a full JRE etc, see the installed components list

Fair explanation, but doesn't seem like a resolution. It's troubling that the sidekick tool in a 50MB image is 2Gigs worth :-|
Is there something that can be done to reduce the size?

**Comment by ekeuus** [comment]
We are using the pubsub emulator in a docker image for our test pipelines and the >2gb size is also a problem for us.
