### ISSUE TITLE
Using `gcloud preview docker` fails

### ISSUE THREAD

**Issue by robertoandrade** [GoogleCloudPlatform/cloud-sdk-docker#23]
Given there's no docker client installed on the container. I normally have to resort to running a new container, installing docker, committing/tagging as a new image and run off of that image instead of the original when in need to run `gcloud preview docker` commands.

It would be nice if either the image already included docker or at least instructions were provided for people to do it in case they need it.

**Comment by proppy** [comment]
The preview components was added in #18, but it may need a rebuild to have `preview docker`.

**Comment by proppy** [comment]
did you consider 'mounting' docker from the host with: `docker run -v /usr/bin/docker:/usr/bin/docker google/cloud-sdk ...` ?

**Comment by robertoandrade** [comment]
Yeah, that's part of what I do, but the problem isn't with that but with the docker client itself, which doesn't exist within the container. So even if you map the socket, the container itself doesn't have access to the `docker` bin in order to delegate the commands.

**Comment by proppy** [comment]
I was suggesting to also map the docker binary, not only the docker socket.

**Comment by robertoandrade** [comment]
hum... interesting idea... but still I'd have to do that either every time I'd run a `gcloud preview docker` command or go thru the same process that I already do on every machine, create a container with those volume mappings, tag it as an image so I can run one-off containers off of it.

Either the gcloud container should have those mapped by default or have docker pre-installed alongside the Cloud SDK inside it?

**Comment by proppy** [comment]
Host volume mapping don't persist when you commit a container, so you'd have to mount the socket everytime anyway.

**Comment by robertoandrade** [comment]
True. what I end up doing for that is adding these volume options to a shell script I use instead of calling gcloud directly.

**Comment by proppy** [comment]
@robertoandrade yes, it would be nice to add some more specific examples about this in README.md

**Comment by ahmetb** [comment]
Closing this, explanation at https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/26#issuecomment-308633286 .
