### ISSUE TITLE
Keep images hosted on Dockerhub as well as gcr.io

### ISSUE THREAD

**Issue by viyh** [GoogleCloudPlatform/cloud-sdk-docker#240]
Just noticed the recent deprecation notice to remove the images from Dockerhub in March 2021. This creates a large amount of unnecessary work in a short time across a lot of projects that I manage. Is there a specific reason that the image can't continue to be hosted on Dockerhub as well as the Google owned registry? Or at least lengthen the timeframe to a year or more so that this can be rolled out piecemeal instead of as a fire drill? It's easy enough to push images both registries, similar to what Amazon does by maintaining their images on both Dockerhub and their own public container registry.

**Comment by willfaris** [comment]
Thanks for the feedback. At this point in time we plan on pushing to both GCR and Dockerhub. We have removed the deprecation notice on google/cloud-sdk's dockerhub page https://hub.docker.com/r/google/cloud-sdk. If we have to stop pushing to Dockerhub in the future we will give another deprecation warning. We do recommend all users switch to GCR to pull these images, the change is simple but we understand any change to infrastructure comes with a cost.
