### ISSUE TITLE
Emulators data in docker volume

### ISSUE THREAD

**Issue by 1Wggb1** [GoogleCloudPlatform/cloud-sdk-docker#241]
Can i store data of the emulators in volume using docker? For example, i would like store data of cloud-firestore-emulator for use after in another container.

**Comment by willfaris** [comment]
I think the best documentation about the firestore emulator is here https://firebase.google.com/docs/emulator-suite/connect_firestore#import_and_export_data

in terms of the docker image you would have to copy data out of the emulator, then copy it out of yout container and then import it into a different container.
