### ISSUE TITLE
Kpt Support in Latest

### ISSUE THREAD

**Issue by runewake2** [GoogleCloudPlatform/cloud-sdk-docker#248]
The `cloud-sdk-docker` README lists `kpt` as a feature of the `latest` version of the image. However `kpt` does not appear to be included with this image.

Additionally, [`kpt` has been added](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/dab6b53147b379f1af9a487379bec856879f99d6) to the `debian_component_based` image but is not listed as available in the README.

**Comment by willfaris** [comment]
kpt will be added to latest in the next release, 332.0.0
