### ISSUE TITLE
Firebase Test Lab new flag/option

### ISSUE THREAD

**Issue by ArcherEmiya05** [GoogleCloudPlatform/cloud-sdk-docker#255]
Good day, I've been [told](https://stackoverflow.com/a/68137271/12204620) by one of the engineers in Firebase Test Lab that there will be new option for gcloud CLI tools where we could now skip re-signing the APK during Robo Test. When can we expect this new feature on gcloud CLI?

Thank you!

**Comment by gerbercj** [comment]
The `--resign` flag is included in gcloud 350.0.0. See https://cloud.google.com/sdk/docs/release-notes#35000_2021-07-27.
