### ISSUE TITLE
security issue : clamAV  detecting Multios.Trojan.ElectroRAT

### ISSUE THREAD

**Issue by JarvisIn** [GoogleCloudPlatform/cloud-sdk-docker#256]
Dear all,

The docker build didn't pass the vulnerability scan - clamAV detected a virus Multios.Trojan.ElectroRAT.

After investigation it appears the virus is located in the binary google-cloud-sdk-359.0.0-linux-x86_64.tar.gz

$ clamscan -a -r '--max-filesize=0' '--max-scansize=0' '--log=clamav-report.txt' --database=$PWD /tmp/google-cloud-sdk-359.0.0-linux-x86_64.tar.gz

Be careful, the scan report can return a typical "OK" if you don't specify right options : '--max-filesize=0' '--max-scansize=0'

It's not clear if this a false positive or a real issue but it seems deep investigation is required.
Thanks

See below report :

/tmp/google-cloud-sdk-359.0.0-linux-x86_64.tar.gz: Multios.Trojan.ElectroRAT-9823393-0 FOUND
/tmp/google-cloud-sdk-359.0.0-linux-x86_64.tar.gz!POSIX_TAR:google-cloud-sdk/bin/anthoscli!...!(735)POSIX_TAR:google-cloud-sdk/lib/third_party/google/cloud/pubsublite_v1/services/topic_stats_service/transports/: Multios.Trojan.ElectroRAT-9823393-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8569094
Engine version: 0.104.0
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 991.70 MB
Data read: 87.95 MB (ratio 11.28:1)
Time: 173.392 sec (2 m 53 s)
Start Date: 2021:09:29 16:34:24
End Date:   2021:09:29 16:37:17

**Comment by JarvisIn** [comment]
When we uncompress the content of google-cloud-sdk-359.0.0-linux-x86_64.tar.gz in a folder and perform a new scan on the folder - the result is OK , no detection of virus anymore.

Strange behavior !

**Comment by gerbercj** [comment]
Thanks for the follow-up update. Looking at the report, the specified folder contains Python code that we publish here:
https://github.com/googleapis/python-pubsublite/tree/main/google/cloud/pubsublite_v1/services/topic_stats_service/transports

You can compare the contents of the tarball with this Github site to confirm that the files are correct.
