### ISSUE TITLE
Docker gcloud CLI doesn't assume instance zone

### ISSUE THREAD

**Issue by chrisyeoward** [GoogleCloudPlatform/cloud-sdk-docker#259]
When run on my local machine (MacOS 10.14), the following command: 

`gcloud compute instances describe <INSTANCE_NAME> --format="value(zone)"`

provides the  output:
```
No zone specified. Using zone [<ZONE> for instance: [<INSTANCE_NAME>].
https://www.googleapis.com/compute/v1/projects/<PROJECT_ID>/zones/<ZONE>
```

Allowing us to update instances in our regional instance group, establishing the zones dynamically. (NB this also applies to the `gcloud compute instances add-metadata` command)

When i run that same command from docker, i receive:
`ERROR: (gcloud.compute.instances.describe) Underspecified resource [<INSTANCE_NAME>]. Specify the [--zone] flag.`

To repro this on docker, I used the Dockerfile:

```
FROM gcr.io/google.com/cloudsdktool/cloud-sdk:alpine

COPY credentials.json .

RUN gcloud auth activate-service-account --key-file credentials.json
RUN gcloud config set project <PROJECT_ID>
RUN gcloud compute instances describe <INSTANCE_NAME> --format="value(zone)"
```

I'm running the same version of gcloud CLI locally and on docker. Exact same service account creds, same commands. 
Apologies if there's something I'm missing, but not sure how to work around this?

**Comment by willfaris** [comment]
Can you show the results of `gcloud config list` on your local machine?

**Comment by chrisyeoward** [comment]
Sure, here's the config for both:

On my local:
```[core]
account = <SERVICE_ACCOUNT>
disable_usage_reporting = True
project = <PROJECT_ID>

Your active configuration is: [default]```

on docker:
```
[component_manager]
disable_update_check = true
[core]
account = <SERVICE_ACCOUNT>
disable_usage_reporting = true
project = <PROJECT_ID>
[metrics]
environment = github_docker_image
```

**Comment by chrisyeoward** [comment]
Is it expected behaviour that the gcloud cli requires the zone flag? From the docs I thought it sounded like it assumed the zone

**Comment by willfaris** [comment]
you need to specify zone to most `gcloud compute ...` commands

you can also set the zone via config though

See 

`gcloud config set --help`

an example

`gcloud config set compute/zone asia-east1-b`

and you can see it with

`gcloud config list`
