### ISSUE TITLE
Please add firebase cli into cloud sdk image

### ISSUE THREAD

**Issue by pdobrzanski** [GoogleCloudPlatform/cloud-sdk-docker#262]
Hello Team,

Could you consider adding firebase CLI into this docker image?
Installed i.e. with https://firebase.google.com/docs/cli#install-cli-mac-linux

We are deploying our firebase/GCP project using mixed gcloud/firebase command CLI. Having one image (without extending it our own) would make our life easier. Also, given the fact that firebase is integrated with GCP it makes sense to have both tools in one image.

**Comment by willfaris** [comment]
Thinking about this.

I can see the convenience of having one image for everything but the default image already has so many things installed and is quite large as it is. So I think we prob not pull in the firebase CLI. You can always extend the image for you use case though. It comes down to our users, how many would want to use the firebase CLI in addition to gcloud.
