### ISSUE TITLE
Unnecessary .backup directory in `:debian_component_based` image

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/cloud-sdk-docker#263]
Hello,

The image contains two copies of the SDK - one before and one after the installation of additional components, which significantly affects the size of the image. We should delete these files because we have full control over the installation process and no one will ever use this copy.
```
$ docker run -ti --entrypoint /bin/bash gcr.io/google.com/cloudsdktool/cloud-sdk:369.0.0-debian_component_based -c "du -sh /google-cloud-sdk/.install/.backup"
502M    /google-cloud-sdk/.install/.backup
```
Image `:latest, :VERSION` may have redundant files as well, because it is very big, but I didn't have time to verify that. We should use [`dive`](https://github.com/wagoodman/dive) to audit this image.
![Screenshot 2022-01-23 at 04 12 45](https://user-images.githubusercontent.com/12058428/150663388-2fba4adc-23c5-43c6-9ca3-7ad70d7f37bd.png)

Best regards,
Kamil Breguła

Related issue: https://github.com/apache/airflow/issues/18913

CC: @willfaris @tswast

**Comment by willfaris** [comment]
This will go out with release 370.0.0

**Comment by mik-laj** [comment]
@willfaris You made a mistake. These files will still be in the image because you created a new layer. You should combine two RUN layers into one to avoid keeping .backup directory in image:
```diff
RUN /google-cloud-sdk/install.sh --bash-completion=false --path-update=true --usage-reporting=false \
	--additional-components app-engine-java app-engine-python alpha beta \
	pubsub-emulator cloud-datastore-emulator app-engine-go bigtable cbt datalab \
	app-engine-python-extras kubectl appctl kustomize minikube nomos skaffold anthos-auth \
-	kpt local-extract
-RUN rm -rf /google-cloud-sdk/.install/.backup/
+	kpt local-extract && \
+	rm -rf /google-cloud-sdk/.install/.backup/

```

**Comment by mik-laj** [comment]
@willfaris I have compiled a comparison after and before you made your change, and also after applying my fix.
```
REPOSITORY    TAG        IMAGE ID       CREATED              SIZE
test-fixed    latest     1b6cd8a85e96   About a minute ago   2.76GB
test-after    latest     e45cb0b6c222   8 minutes ago        3.23GB
test-before   latest     6c2858e945cf   12 minutes ago       3.23GB
debian        buster     8a94f77c4ac3   5 weeks ago          114MB
docker        19.03.11   0bfe00e7bcd5   20 months ago        211MB
```

**Comment by mik-laj** [comment]
@gerbercj  WDYT?

**Comment by willfaris** [comment]
before and after sizes

wfaris@wfaris:~/cloud-sdk-docker/debian_component_based$ docker image inspect bigger --format {{.Size}}
3217117875
wfaris@wfaris:~/cloud-sdk-docker/debian_component_based$ docker image inspect smaller --format {{.Size}}
2753368482

**Comment by mik-laj** [comment]
@willfaris  Thank you!
