### ISSUE TITLE
Missing logs in pubsub emulator

### ISSUE THREAD

**Issue by connerbw** [GoogleCloudPlatform/cloud-sdk-docker#264]
I am looking for logs when developing. When I start with:

`gcloud beta emulators pubsub start --project=abc --host-port=0.0.0.0:8085 --verbosity=debug --log-http`
 
I see:

```
DEBUG: Running [gcloud.beta.emulators.pubsub.start] with arguments: [--host-port: "<googlecloudsdk.calliope.arg_parsers.HostPort object at 0x7fee8ad087f0>", --log-http: "true", --project: "abc", --verbosity: "debug"]
DEBUG: Found Cloud SDK root: /google-cloud-sdk
Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Feb 21, 2022 7:36:52 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Feb 21, 2022 7:36:53 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8085
[pubsub] Feb 21, 2022 7:37:16 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
```

**_Expected:_**
At this point, when I start programmatically interacting with the emulator, I am expecting logs, I want proof that something is happening.

**_Actual:_**
Instead it stays like this until I shut down.

-=-=-

Seen in a few places already?

- https://groups.google.com/g/cloud-pubsub-discuss/c/ikXsMlrMg0U
- https://stackoverflow.com/questions/66631222/pubsub-emulator-v331-slf4j-error-on-start-no-logging/66631906#66631906
- https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/260

**Comment by willfaris** [comment]
I am going to close this issue as this issue tracker is for issues related to the the docker images.  To log an issue with a particular emulator please post this to https://issuetracker.google.com/issues/new?component=187143
