### ISSUE TITLE
Cloud Datastore emulator not available on debian_component_based

### ISSUE THREAD

**Issue by takanakahiko** [GoogleCloudPlatform/cloud-sdk-docker#268]
When I try to use the Cloud Datastore emulator with debian_component_based, I get the following message:

```
$ docker run -it --rm gcr.io/google.com/cloudsdktool/google-cloud-cli:376.0.0-debian_component_based gcloud --project=unittest beta emulators datastore start --host-port=0.0.0.0:8081 --no-store-on-disk --consistency=1.0

ERROR: (gcloud.beta.emulators.datastore.start) To use the Google Cloud Datastore emulator, a Java 8+ JRE must be installed and on your system PATH
```

It seems that it can be solved by including Java 8+ JRE in debian_component_based, but is it possible to support it?

**Comment by willfaris** [comment]
Why not use

gcr.io/google.com/cloudsdktool/google-cloud-cli:376.0.0-emulators? do you need an ARM image?

**Comment by takanakahiko** [comment]
> do you need an ARM image?

Yes

**Comment by willfaris** [comment]
We should be able to publish an arm version of the emulators image... I will have to investigate if all the emulators will work on arm.

**Comment by willfaris** [comment]
Going to go ahead and close this issue, the emulators image should support ARM with release 379.0.0, 379.0.0 is scheduled to be released March 29th, 2022.
