### ISSUE TITLE
Support for PHP composer v2

### ISSUE THREAD

**Issue by CodecloudsSaddam** [GoogleCloudPlatform/cloud-sdk-docker#271]
We are facing gcloud app deployment issue after updating the composer repository schema to the latest version. Please see
![image](https://user-images.githubusercontent.com/53344682/162159900-517898c4-8cd4-4a09-847f-353368b59595.png)
![image](https://user-images.githubusercontent.com/53344682/162160624-763b0c1d-d0e0-48aa-8d11-830371142081.png)
![image](https://user-images.githubusercontent.com/53344682/162160511-600dc6ce-81f0-4c17-bfba-8d84fd219d4a.png)

After some R&D I found that the google/cloud-sdk:alpine and google/cloud-sdk:latest images have been using PHP composer version 1 and the v1 does not support some of the latest composer schemas.

Please advise how can we resolve the above issue.

**Comment by willfaris** [comment]
can you show where the reference to google/cloud-sdk:alpine and|or google/cloud-sdk:latest exists

**Comment by CodecloudsSaddam** [comment]
Hi @willfaris this is a GitLab CI/CD pipeline script
![image](https://user-images.githubusercontent.com/53344682/162266485-24134ecc-8260-405f-b18a-887157db01a5.png)

**Comment by willfaris** [comment]
Closing this issue for now, if you have more information please re-open the issue.
