### ISSUE TITLE
Update dockerfile to debian bullseye

### ISSUE THREAD

**Issue by charlesomer** [GoogleCloudPlatform/cloud-sdk-docker#272]
Hi,

I am trying to use Vagrant with this plugin: https://github.com/mitchellh/vagrant-google however it requires ruby v2.6 or above. v2.5 is now EOL: https://www.ruby-lang.org/en/downloads/.

Would it be possible to update the docker image to use bullseye? Buster uses 2.5 whereas Bullseye uses 2.7.

Thank you
Charles

**Comment by willfaris** [comment]
https://wiki.debian.org/DebianReleases shows buster is EOL ~2022-08 so we should move the buster based images to bullseye.

**Comment by bobidle** [comment]
There was a rolling back (f259e77a70e6f9d687aea0e239e08e845989866e, 3481e2d1b229cf274ef6213234eaef5187ce0ae4) to the Debian Buster images, as the Debian Bullseye images broke the release process somehow.
