### ISSUE TITLE
python shortcut removed in 385.0.0

### ISSUE THREAD

**Issue by Letme** [GoogleCloudPlatform/cloud-sdk-docker#273]
With the commit d97cf72c4c50b216a139e693f8d62b2ef6aec921 the `python` shortcut was removed and `python3` should be used in your commands. This seems like a side-effect, so in reality I think the `python` should now link to `python3`.

**Comment by bobidle** [comment]
It is possible to e.g. install the package `python-is-python3` to add the suggested symlink.

```
FROM google/cloud-sdk:latest

RUN apt update \
 && apt install -y python-is-python
```

But i guess that should not be the default. A quote from the package description:

> Starting with the Debian 11 (bullseye) and Ubuntu 20.04 LTS (focal) releases, all python packages use explicit python3 or python2 interpreter and do not use unversioned /usr/bin/python at all. Some third-party code is now predominantly python3 based, yet may use /usr/bin/python. 
>
> This is a convenience package which ships a symlink to point the /usr/bin/python interpreter at the current default python3. It may improve compatibility with other modern systems, whilst breaking some obsolete or 3rd-party software. 
>
> No packages may declare dependencies on this package. 

https://packages.debian.org/bullseye/python-is-python3

**Comment by cloudsdkdocker** [comment]
Closing as having python reference python3 is not a recommended pattern per bobidles comment above.
