### ISSUE TITLE
ppc64le CLI tools

### ISSUE THREAD

**Issue by sumitd2** [GoogleCloudPlatform/cloud-sdk-docker#278]
Hi team,

We require the ppc64le version of the tar file:
`https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz`

Can you point us to its code? Or if this is the right repo to ask for it, can you provide us with the tar file?

Thank you.

**Comment by sumitd2** [comment]
@s4shyam95 Can you please help us here? We also need the gke-gcloud-auth-plugin for ppc64le.

**Comment by cloudsdkdocker** [comment]
We're sorry, but the Cloud SDK doesn't currently support the ppc64le architecture, nor does the gke-gcloud-auth-plugin. There currently aren't any plans to support this architecture. I have gone ahead and have created an internal feature request to support this architecture, and if we see increased interest or need for it we will prioritize supporting it in the future.
