### ISSUE TITLE
 google/cloud-sdk ARM arch support

### ISSUE THREAD

**Issue by lunfardo** [GoogleCloudPlatform/cloud-sdk-docker#283]
Please provide native image support for M1 laptops

**Comment by lunfardo** [comment]
seems like you are already working on it

**Comment by maelvls** [comment]
Multi-arch images (including `linux/arm64`) are now available: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/280#issuecomment-1273615171.

**Comment by jochenschneider** [comment]
Only cloud-cli images seem to have arm64 support, not cloud-sdk images.
