### ISSUE TITLE
CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable

### ISSUE THREAD

**Issue by xdekasx** [GoogleCloudPlatform/cloud-sdk-docker#284]
Seems that the image has not the new way to use kubectl.

The full message is:

_CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke_

_WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke_

This image will handle this or another implementation will be needed?

Thank you,

**Comment by albertnavas** [comment]
Same question about the image and the new authentication method for kubectl

**Comment by cloudsdkdocker** [comment]
gke-gcloud-auth-plugin has been added to both the standard and component based debian images. Please reopen if any issues are encountered.

**Comment by xdekasx** [comment]
First of all, thank you for your response.

Indeed, I can see the gke-gcloud-auth-plugin is installed, but using `kubectl` from the docker image the warning is still there.

Here the path I follow:

Init the container
`docker run -it gcr.io/google.com/cloudsdktool/google-cloud-cli:latest /bin/bash`

Inside container I login to my GKE cluster
`gcloud auth login`
`gcloud config set project [project-name]`
`gcloud container clusters get-credentials [cluster-name] --zone [zone] --project [project-name]`

Once I'm authenticated simply I run a kubectl command as `kubectl get pods` and the warning still there.

_WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke_

---

Correct me if I'm wrong but I think the plugin `kubectl` is not installed via `gcloud` but as system application. 

It is possible `kubectl` is not using `gke-gcloud-auth-plugin`?

![image](https://user-images.githubusercontent.com/10883527/190406893-154fba4c-c238-4182-b4c0-8f684105237f.png)

![image](https://user-images.githubusercontent.com/10883527/190407298-02723e52-0e15-429f-8dba-6c419dcc2933.png)

**Comment by cloudsdkdocker** [comment]
Thank you for the detailed comment. After some investigation it seems that kubectl will not default to using the new plugin until v1.26, with the current version being 1.25 https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

If you would like to force an older version of kubectl to use the new plugin there are instructions in the link above.

Having added the new plugin to these images they should now be future-proofed for when 1.26 comes out. As such I will re-close this issue.
