### ISSUE TITLE
Breaking gcp auth change in latest image 412.0.0

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [GoogleCloudPlatform/cloud-sdk-docker#298]
<img width="923" alt="Screenshot 2022-12-14 at 17 00 46" src="https://user-images.githubusercontent.com/17408117/207659540-111a5767-7a22-4912-a4be-2529fc0d51f8.png">

gke-gcloud-auth-plugin apeares not to be installed, and on manual installation via apt the installation fails with the following

<img width="1057" alt="Screenshot 2022-12-14 at 17 03 50" src="https://user-images.githubusercontent.com/17408117/207660210-2d11d759-7506-4503-b758-fd1b6ba00255.png">

**Comment by YonathanZetune** [comment]
Hi, it appears you are trying to use the `-sdk-` version with the `-cli-` package. `cli` is the current version of this package you are using, therefore `google-cloud-cli-gke-gcloud-auth-plugin` is the correct name. Could you please try with: `apt-get install google-cloud-cli-gke-gcloud-auth-plugin`? [More](https://issuetracker.google.com/issues/241218589)

**Comment by JamesTiberiusKirk** [comment]
right, fixing the package name worked for installed the plugin (and it was already installed)
```
$ apt-get install google-cloud-cli-gke-gcloud-auth-plugin
Reading package lists...
Building dependency tree...
Reading state information...
google-cloud-cli-gke-gcloud-auth-plugin is already the newest version (412.0.0-0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

however, it seems like this was caused because of a missing env variable 
`export USE_GKE_GCLOUD_AUTH_PLUGIN=True`
after setting this, everything was working as normal

**Comment by JamesTiberiusKirk** [comment]
Feel free to close this ticket now

**Comment by brattonj-oci** [comment]
I know this is closed now, but its still a breaking change to have to add this environment variable.

**Comment by JamesTiberiusKirk** [comment]
@brattonj-oci if I know correctly, this isnt a breaking change because we were always meant to use this env variable. Prior to this change, missing this env variable would trigger the deprication warming I think. (aka, i think we were always meant to have it)
