### ISSUE TITLE
Installing NumPy

### ISSUE THREAD

**Issue by ferrarimarco** [GoogleCloudPlatform/cloud-sdk-docker#299]
Hi folks!

Given that [installing NumPy is recommended by the IAP docs](https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth) to increase the upload bandwidth, is it something we can include in the Cloud SDK image?

Thanks!

**Comment by cloudsdkdocker** [comment]
Hi ferrarimarco,

Given numpy itself is ~85mb of space and it is not necessary for core gCloud functionality, we will not be adding it to the docker images. 

The goal of the docker images is to provide baseline functionality to a wide variety of users, each with specific usecases in mind. The size of the docker images is already an issue for most users, so we don't want to  significantly increase the size of the images to cater to a very specific usecase.

We recommend to all users to use these docker images as a starting point to then layer or construct their own images to suit their specific goals.

**Comment by ferrarimarco** [comment]
Thanks for the insight!
