### ISSUE TITLE
Zscaler support

### ISSUE THREAD

**Issue by paneerlovr** [GoogleCloudPlatform/cloud-sdk-docker#321]
Is there a way to allow the SDK to install using a custom trusted CA bundle?  My company uses zscaler (man in the middle eavesdropping) and I'm trying to get the GCP CLI installed, but I get errors like this:

requests.exceptions.SSLError: HTTPSConnectionPool(host='dl.google.com', port=443): Max retries exceeded with url: /dl/cloudsdk/channels/rapid/components-2.json (C
aused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
Google Cloud CLI installer will now exit.

**Comment by bobidle** [comment]
@paneerlovr what kind of installer do you use? You do not use a `cloud-sdk` docker image by chance (this repository is about the Google CLI/SDK Docker images)?

**Comment by paneerlovr** [comment]
@bobidle You are correct, I'm so sorry about this post, I meant to comment on the cloud SDK without docker, sorry!

**Comment by anindyatahsin** [comment]
Closing this issue as this is not related to gcoud cli/sdk docker image
