### ISSUE TITLE
Buildx missing

### ISSUE THREAD

**Issue by pfuhrmann** [GoogleCloudPlatform/cloud-sdk-docker#331]
Because the base docker version was upgraded out of nowhere to v24 from V20, buildx has to be installed separately. That's a rather huge breaking change.

https://docs.docker.com/build/architecture/#install-buildx

> Docker Engine version 23.0 and later requires that you install Buildx from a separate package. 

**To Reproduce**

Add a new build project and set the image to `cloud-sdk:432.0.0-slim`

use the following to try and build any docker image:
```bash
export DOCKER_BUILDKIT=1
docker build .
```

See error:
```bash
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

EDIT: Added the steps to reproduce the issue.

**Comment by pfuhrmann** [comment]
It seems it was reverted now: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/373fae09badb76192aff86e4ba0f76ad9bd819c1

However, it's concerning what is the development process here, seems there is no process.

**Comment by cloudsdkdocker** [comment]
The images have been rebuilt and launched. The initial fixes introduced errors into the build process that weren't identified until this morning.

The impetus of this update are a number of CVEs within the (now) current version of docker engine, including a Critical CVE blocking some customers. Since no breakages in the CLI itself were identified the change was launched. This obviously lead to breakages in workstreams outside direct Cloud CLI CUJs.

The Cloud CLI team currently lacks strong transparency on how these images are being used beyond what we test and validate the CLI itself for, so while we're attempting to balance CVE remediation against preventing impact of user workflows we're somewhat stumbling in the dark.

All of this is being considered as we're looking towards what the future of these images looks like. What would be valuable input to this planning process would be an high level explanation of what workflows these changes broke for you all if you don't mind providing it. We'll be doing further outreach to users beyond this github issue, but for now any input is valuable.

**Comment by pfuhrmann** [comment]
Hi, thank you for your reply.

I think I have provided sufficient info in the initial issue description. Buildx is a very common part of many build systems. For example, without buildx, there is no way to handle secrets securely inside container images. I do fully agree that Docker v20 is outdated and would prefer v24, however not the way it was done yesterday.

For more context, the same thing happened to your counterparts at AWS [1]. The way they solved it, is they added buildx tool into their image [2]. Could you do the same to prevent this breaking change for many users of your base image?

[1] https://github.com/aws/aws-codebuild-docker-images/issues/625
[2] https://github.com/aws/aws-codebuild-docker-images/pull/626/files

**Comment by bobidle** [comment]
@pfuhrmann opened a pull request with Docker v24.0.1 including buildx. Could you build the docker image and check if `docker` and `docker buildx` works as expected?

e.g.
```
docker build -t local/cloud-sdk:alpine --build-arg CLOUD_SDK_VERSION=430.0.0 .
``` 

included buildx version
```
$ docker run --rm -it local/cloud-sdk:alpine docker buildx version
github.com/docker/buildx v0.10.5 86bdced7766639d56baa4c7c449a4f6468490f87
```

**Comment by pfuhrmann** [comment]
Can confirm, it seems to work! Tested with the following command:

```bash
docker run -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
  -v .:/tmp/build \
  --rm -it \
  local/cloud-sdk:alpine sh -c "export DOCKER_BUILDKIT=1 && docker build /tmp/build"

---

 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                          0.0s
 => => transferring dockerfile: 1.03kB                                                                                                                                                                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                             0.0s
 => => transferring context: 203B                                                                                                                                                                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/alpine:3.18.0                                                                                                                                                                                                                                                                                              
...
```

The same command fails when using the "broken" digest instead, i.e.:
```bash
docker run -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
  -v .:/tmp/build \
  --rm -it \
  google/cloud-sdk@sha256:0c0c557139ba6a3e00bab3ebdcbf0012d130c5dcc3411e903ea387679137e79b sh -c "export DOCKER_BUILDKIT=1 && docker build /tmp/build"

---

ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```
