### ISSUE TITLE
Entrypoint doesn't work in Dockerfile from version 430.0.0

### ISSUE THREAD

**Issue by RafaelHGBotelho** [GoogleCloudPlatform/cloud-sdk-docker#335]
Newer versions of the google/cloud-sdk image, starting from 430.0.0 do not validate entrypoint in Dockerfile Build, only in deployment.yaml with `command` in GKE, K8s in general.

I did some tests and with `google/cloud-sdk:429.0.0` it worked. It is not necessary to pass the `command` in the deployment.yaml, only in the Dockerfile normally in version 429.0.0.

**Comment by bobidle** [comment]
@RafaelHGBotelho could you share a public or sample Docker image or Dockerfile where you could reproduce the issue?

**Comment by anindyatahsin** [comment]
@RafaelHGBotelho closing the issue for inactivity. If the issue is still present in the latest docker image (v455.0.0) please create a new issue with more details (preferably steps to reproduce the issue)
