### ISSUE TITLE
Upgrade Debian image to bookworm 

### ISSUE THREAD

**Issue by muffl0n** [GoogleCloudPlatform/cloud-sdk-docker#345]
Currently, Debian `bullseye` is used. It should be updated to `bookworm`.

**Comment by bobidle** [comment]
@muffl0n last time i tried the upgrade of the Google Cloud SDK Images to Debian Bookworm, some SDK packages could not be used. Some of them are use in the provided images. Because of missing deps like Java v8 and Python v2.7 in Debian Bookworm.

I will try the upgrade next week again and if some packages are not installable i will contact the Google support about it.

**Comment by muffl0n** [comment]
Awesome! Thanks for your feedback! ❤️

**Comment by bobidle** [comment]
The upgrade is possible but some default package (e.g. of the latest image) have to be removed. e.g.:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  google-cloud-cli-app-engine-java : Depends: openjdk-8-jdk but it is not installable or
                                              openjdk-11-jdk but it is not installable
  google-cloud-cli-app-engine-python : Depends: python2.7 but it is not installable
  google-cloud-cli-datastore-emulator : Depends: openjdk-8-jdk but it is not installable or
                                                 openjdk-11-jdk but it is not installable
  google-cloud-cli-firestore-emulator : Depends: openjdk-8-jdk but it is not installable or
                                                 openjdk-11-jdk but it is not installable
  google-cloud-cli-pubsub-emulator : Depends: openjdk-8-jdk but it is not installable or
                                              openjdk-11-jdk but it is not installable

Unable to correct problems, you have held broken packages.
```

If the packages should be included in the future, we have to wait for updated deps of the CLI/SDK Debian/Ubuntu packages.

I am not sure if that braking changes should be applied to the docker images atm.

e.g. App Engine drops support for Python 2.7 on 2024-01-30
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#python

**Comment by cloudsdkdocker** [comment]
+1 on these packages still blocking update. The inclusion of these non-default components is preventing us from ensuring this image is up to date and minimizing its CVE surface area. We have been exploring what our strategy with these images will be going forward given these persistent issues. I will likely open a discussion with some proposals to gauge feedback from users very soon to help inform our next steps!

**Comment by muffl0n** [comment]
Hey @bobidle thanks for your work! Unfortunately I can't test this as we moved to using alpine based images. Sorry. :|

**Comment by anindyatahsin** [comment]
All the debian based images are upgraded to Debian 12.
