### ISSUE TITLE
apt-get update fails with 503 service unavailable

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/cloud-sdk-docker#35]
Hi,
The command 'apt-get update' errors with 503 Service Unavailable from local machine, however works fine on GCE and GAE. Wasn't sure if this was intended.  My unit tests fail because of this error. Wondering if we could get an explain. Thanks!

Trace:
Step 4 : RUN apt-get update
 ---> Running in 36449fba4b2c
Ign http://gce_debian_mirror.storage.googleapis.com jessie InRelease
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://gce_debian_mirror.storage.googleapis.com jessie-updates InRelease
Ign http://gce_debian_mirror.storage.googleapis.com jessie Release.gpg
Ign http://gce_debian_mirror.storage.googleapis.com jessie-updates Release.gpg
Ign http://gce_debian_mirror.storage.googleapis.com jessie Release
Ign http://gce_debian_mirror.storage.googleapis.com jessie-updates Release
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [216 kB]
Ign http://gce_debian_mirror.storage.googleapis.com jessie/main amd64 Packages/DiffIndex
Ign http://gce_debian_mirror.storage.googleapis.com jessie-updates/main amd64 Packages/DiffIndex
Err http://gce_debian_mirror.storage.googleapis.com jessie/main amd64 Packages
  503  Service Unavailable
Err http://gce_debian_mirror.storage.googleapis.com jessie-updates/main amd64 Packages
  503  Service Unavailable
Fetched 279 kB in 4s (62.2 kB/s)
W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie/main/binary-amd64/Packages  503  Service Unavailable

W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie-updates/main/binary-amd64/Packages  503  Service Unavailable

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100

Thanks!

**Comment by ahmetb** [comment]
I am assuming this was probably an outage on the apt repository. We'll have images tagged soon, so you don't necessarily build it from the Dockerfile every time in your builds/tests.
