### ISSUE TITLE
Are you planning to host the image on pkg.dev?

### ISSUE THREAD

**Issue by honahuku** [GoogleCloudPlatform/cloud-sdk-docker#355]
Container Registry has been [deprecated](https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation) and will reach EOL in May 2024. Are there any plans for these images to be hosted on pkg.dev (Artifact Registry)?

**Comment by cloudsdkdocker** [comment]
These images were migrated to Artifact Registry about a year ago, gcr.io now redirects to AR rather than CR: https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

**Comment by artemy** [comment]
@cloudsdkdocker is this redirect a permanent solution or there are plans to provide `pkg.dev` container URLs in the future?
