### ISSUE TITLE
Include app-engine-php

### ISSUE THREAD

**Issue by heskethm** [GoogleCloudPlatform/cloud-sdk-docker#36]
In the current version of Cloud SDK (100.0.0), app-engine-php is not included by default.

However, when I attempt to install manually with `gcloud components install app-engine-php`, the component manager has been disabled:

    ERROR: (gcloud.components.install) The component manager is disabled for this installation

Could app-engine-php be added to the Dockerfile, as [app-engine-python and app-engine-java are](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/Dockerfile#L11)?

**Comment by p13eater** [comment]
Turns out you can use this with app-engine-php without any updates

Example:
`docker run --rm  -p 8080:8080 -p 8000:8000 -v `pwd`:/app google/cloud-sdk dev_appserver.py --php_executable_path=/usr/bin/php5-cgi --host=0.0.0.0 --admin_host=0.0.0.0 /app`
