### ISSUE TITLE
Tag releases of Docker images with versions

### ISSUE THREAD

**Issue by devth** [GoogleCloudPlatform/cloud-sdk-docker#38]
Latest happens to be erroring for me (looks like something in kubectl 1.2 is busted: it expects json when `~/.kube/config` is actuall yaml). Would be convenient to use `1.1`.

**Comment by whitecolor** [comment]
This is needed. Still no tags on https://hub.docker.com/r/google/cloud-sdk/

**Comment by ahmetb** [comment]
cc: @salrashid123

**Comment by max-vogler** [comment]
The README is wrong on this point -- `155.0.0` is not a published tag in the Docker Registry.
> Supported tags and respective Dockerfile links
> [155.0.0, latest] (Dockerfile)

**Comment by salrashid123** [comment]
We can close this one out.  The dockerhub and github is now tagged (though we need to manually tag+push to github to trigger the tagged builds for now).
