### ISSUE TITLE
add .ssh volume

### ISSUE THREAD

**Issue by nightlyone** [GoogleCloudPlatform/cloud-sdk-docker#40]
Which would be very useful for GCE and avoids regenerating new SSH keys in 

`gcloud compute --project REDACTED ssh ctrexporter-live --quiet --command 'hostname'`

**Comment by ahmetb** [comment]
You can mount your ssh directory as `-v ~/.ssh:/root/.ssh`. The image does not need any changes. The VOLUME command in the Dockerfiles are purely for documentation.
