### ISSUE TITLE
Add Instructions for creating service account with "necessary scopes" on GCE

### ISSUE THREAD

**Issue by sijnc** [GoogleCloudPlatform/cloud-sdk-docker#41]
RE: "If you enable a Service Account with the necessary scopes, there is no need to auth or use a config volume"

What are the necessary scopes?

Thanks...

**Comment by ahmetb** [comment]
When you login with your Google account at `gcloud auth login`, your account probably has Owner permissions on the project. (You can check IAM/Admin page on Console to make sure.) So if you create a service account with same permissions you can use the key of that Service Account inside the container to authenticate using `gcloud auth activate-service-account --key-file=/path/to/key.json` (make sure you mount your host filesystem, that has the key, to the container).
