### ISSUE TITLE
Bigtable component not installed

### ISSUE THREAD

**Issue by timkaye11** [GoogleCloudPlatform/cloud-sdk-docker#46]
refs https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/42

Attempting to run the bigtable emulator results in this warning: 
```
You cannot perform this action because this Cloud SDK installation is 
managed by an external package manager.  If you would like to get the 
latest version, please see our main download page at:
  
https://cloud.google.com/sdk/

ERROR: (gcloud.beta.emulators.bigtable.start) The component manager is disabled for this installation
```

I believe the `bigtable` component is missing from the Dockerfile, and will be fixed by this patch: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/compare/master...timkaye11:master

**Comment by tswast** [comment]
Cool, feel free to send a pull request. You will need to sign the Google CLA if you haven't already (googlebot should ask you for it).

**Comment by timkaye11** [comment]
awesome
