### ISSUE TITLE
Curl broken after last build

### ISSUE THREAD

**Issue by zabandija123** [GoogleCloudPlatform/cloud-sdk-docker#488]
Hi folks, curl command using the latest image tag fails with error:

> curl: (6) getaddrinfo() thread failed to start

Tried prior images and it's working good. It broke after we pulled the image that was built recently.

**Comment by anindyatahsin** [comment]
I can't seem to reproduce the issue  `curl` seem to be working for me.

![Screenshot 2024-10-15 at 4 14 54 PM](https://github.com/user-attachments/assets/e59909be-904e-4983-85d5-afcae78432dc)

Can you give me the specific command that was failing?

**Comment by zabandija123** [comment]
I'm sorry I thought this was the repo for **google/cloud-sdk:latest** docker image.

**Comment by todd-zarla** [comment]
Just adding some notes here in case others stumble across this problem. I don't have a solution besides using the previous version of the container image.

@zabandija123 This does appear to be the correct repository. The tags seem to be aliases:

```
REPOSITORY                                         TAG       IMAGE ID       CREATED        SIZE
gcr.io/google.com/cloudsdktool/cloud-sdk           latest    28048d7b5bf6   13 hours ago   3.16GB
gcr.io/google.com/cloudsdktool/google-cloud-cli    latest    28048d7b5bf6   13 hours ago   3.16GB
gcr.io/google.com/cloudsdktool/cloud-sdk           <none>    ea60756e26cc   2 weeks ago    2.93GB
```

I ran into a similar problem with `curl` a few weeks ago, `f99afe5032dd` fails but `a1df5b4217e3` works:
```
REPOSITORY                                         TAG       IMAGE ID       CREATED        SIZE
gcr.io/cloud-builders/gcloud                       latest    f99afe5032dd   3 weeks ago    2.94GB
gcr.io/cloud-builders/gcloud                       <none>    a1df5b4217e3   4 weeks ago    3.01GB
```

Based on this [README](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/gcloud/README.md), switching from `gcr.io/cloud-builders/gcloud` to `gcr.io/google.com/cloudsdktool/cloud-sdk` resolved the issue at the time.

Seeing different behaviour on two different GCP VMs that have both versions of both container images. One of them works fine with any version. The other exhibits the `curl: (6) getaddrinfo() thread failed to start` problem only in the latest versions but not in the older versions. The closest thing I could find was https://github.com/GoogleCloudPlatform/cloud-builders/issues/1014 but that is about `curl` missing entirely from the image.
