### ISSUE TITLE
Latest alpine doesn't contain python

### ISSUE THREAD

**Issue by LuigiCerone** [GoogleCloudPlatform/cloud-sdk-docker#498]
How to reproduce:

```bash
docker run -it --platform linux/amd64 google/cloud-sdk:alpine python
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python": executable file not found in $PATH: unknown.
```

while previous tag:

```bash
docker run -it --platform linux/amd64 google/cloud-sdk:502.0.0-alpine python
Python 3.11.10 (main, Sep 11 2024, 09:58:40) [GCC 13.2.1 20231014] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

From the docs [here](https://cloud.google.com/sdk/docs/downloads-docker?hl=en#components_installed_in_each_tag) alpine should contain `python`.

EDIT: 

I just saw #497, and I think these issues are related.

**Comment by anindyatahsin** [comment]
python 3.11 was manually installed in the latest alpine image to address some compatibility issue of gsutil component with python 3.12. As a result the `python` path was no longer available in the latest docker image. However, if you need python, you can use it with python3 command. 

```
docker run -it --platform linux/amd64 google/cloud-sdk:alpine python3
```
Should work. We'll fix the path in our next gcloud release 504.0.0.
