### ISSUE TITLE
ERROR: Reachability Check failed.

### ISSUE THREAD

**Issue by dominicbarnes** [GoogleCloudPlatform/cloud-sdk-docker#51]
For some reason, I can't get the `google-cloud-sdk` library to make any API requests against gcloud. The minimum reproduction steps for me look like this:

```
$ docker run -it google/cloud-sdk gcloud init
Welcome! This command will take you through the configuration of gcloud.

Your current configuration has been set to: [default]

Network diagnostic detects and fixes local network connection issues.
Checking network connection...done.
ERROR: Reachability Check failed.
    Cannot reach https://cloudresourcemanager.googleapis.com/v1beta1/projects (ServerNotFoundError)
    Cannot reach https://www.googleapis.com/auth/cloud-platform (ServerNotFoundError)
    Cannot reach https://dl.google.com/dl/cloudsdk/channels/rapid/components-2.json (ServerNotFoundError)
Network connection problems may be due to proxy or firewall settings.


Do you have a network proxy you would like to set in gcloud (Y/n)?  n

ERROR: Network diagnostic (0/1 checks) failed.
```

This is just the bare minimum, I'm trying to set up a more sophisticated container but can't get any of the commands that hit the gcloud API to succeed. (eg: `gcloud components list`, `bq ls`, etc) They all fail with similar `ServerNotFoundError` errors.

I am not behind a proxy or anything, as I get the same result at the office and at home. Also, when I create an image from this container and then access the shell I can `ping` the above hosts just fine.

**Comment by whitecolor** [comment]
add `--dns 8.8.8.8` to your run command.

**Comment by dominicbarnes** [comment]
That seems to help, but it's weird that I need to do that at all. I'd consider adding `--dns 8.8.8.8` a workaround, but probably not a fix.

**Comment by ahmetb** [comment]
I just tried with the latest `alpine/Dockerfile` we have and it worked smoothly just fine. It's probably an environment/setup issue with Docker. I'll close this, let us know if this is still the case.
