### ISSUE TITLE
cloud shell gcloud compute ssh

### ISSUE THREAD

**Issue by chad-autry** [GoogleCloudPlatform/cloud-sdk-docker#56]
What needs to be done to get 'gcloud compute ssh' in the docker container to auto-authenticate when run from cloud shell?

Passing in --net=host -e DEVSHELL_CLIENT_PORT=$DEVSHELL_CLIENT_PORT gets it to generate an SSH key, but then it asks for a password (unlike when I run gcloud compute ssh directly within cloud shell)

**Comment by ahmetb** [comment]
I'm not familiar with the inner workings of `gcloud compute ssh` but I assume it will need `ssh` and `ssh-keygen` installed in the Docker image, I am not sure these packages there. `ssh` certainly not installed in the new alpine-based image we're about to publish. What error are you seeing? Do other commands work fine?

**Comment by chad-autry** [comment]
No errors, just that it prompts me for a password unlike when I run the command directly on gcloud.
Same issue when I run from my own image https://github.com/chad-autry/wac-gce-ansible

The whole purpose there was to package an ansible install into docker, but in the end I've installed ansible to my gcloud directory (with a script imitating the ssh command, but internally using gcloud compute ssh for the auto-authentication).

**Comment by salrashid123** [comment]
@chad-autry 

Looks like the README currently doens't show how to map your credential volume into a container. 

the procedure is described in [this article](https://medium.com/google-cloud/google-cloud-sdk-dockerfile-861a0399bbbb)   (specifically under `Run gcloud cli without installing SDK locally`).  I'll separately update the readme in this repo to describe this procedure ot map credentils over.  Note, once you create a volume w/ your creds in it, please handle it w/ care!

anyway, if you've initalized gcloud already on a laptop and have creds locally, you can ssh in w/ a similar technique:

```
$ docker run -ti -v ~/.ssh:/root/.ssh -v ~/.config/gcloud:/root/.config/gcloud google/cloud-sdk gcloud compute ssh $USER@janus --project your_projectID --zone us-central1-a
```

then i'm logged in to the remote

```
srashid@janus:~$ 
```

LMK if this works for you (i'll close this out then but update the readme anyway)
