### ISSUE TITLE
New Issue - Affecting Datalab

### ISSUE THREAD

**Issue by dovy** [GoogleCloudPlatform/cloud-sdk-docker#57]
Thought it was something I did, but suddenly I can't pull the datalab image.

`gcloud docker pull gcr.io/cloud-datalab/datalab-gateway`

Produces:
```
ERROR: (gcloud.docker) unrecognized arguments:
  pull
  gcr.io/cloud-datalab/datalab-gateway
```

Looks like someone had a bad line somewhere...

**Comment by tswast** [comment]
This error is caused by a change in the Cloud SDK. There needs to be a `--` between `docker` and `pull`.

I think you need to do

```
gcloud docker -- pull gcr.io/cloud-datalab/datalab-gateway
```

See the docs for [pulling an image from container registry](https://cloud.google.com/container-registry/docs/pulling)

**Comment by dovy** [comment]
The issue is in the datalab image. I just figured that out. Thanks for the prompt feedback. I'll report what they must do.

**Comment by spacebel** [comment]
I get this exception even using double dash in the command.
Using version 210 of the Cloud SDK.
