### ISSUE TITLE
Use --volume $HOME/.config instead of --volumes-from

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-sdk-docker#61]
I am opening this issue to see if people are interested in suggesting users something like:

    alias gcloud="docker run --rm -it -v $HOME/.config/:/.config/ -v /:/rootfs gcloud"

Instead of doing the named-container and `--volumes-from` dance.

I am trying to get this idea to work but I am confused that when I login, I don't see `$HOME/.config/` in `docker diff` results. It also looks like there are other paths the gcloud state is stored, such as `$HOME/.boto` and `$HOME/.gsutil/`. If everything was under one place (e.g. `$HOME/.config/gcloud`) there would be no need to run a `gcloud init` container and installation/usage would be as simple as creating an alias.

Thoughts?

cc: @tswast @salrashid123

**Comment by salrashid123** [comment]
You can use the volume-from to stash a known cred+config now (eg. using a different service account with a different project etc)  (I realize you can do the same with [--configuration](https://cloud.google.com/sdk/gcloud/reference/config/configurations/)  parameter of gcloud using your local .config/gcloud folder.

With the proposed Alpine [Dockerfile](https://github.com/salrashid123/cloud-sdk-docker/blob/master/alpine/Dockerfile),  you can run the alias above too: 

```bash
$ docker run --rm -it -v $HOME/.config/:/.config/ salrashid123/cloud-sdk-docker gcloud config list
[component_manager]
disable_update_check = false
[compute]
zone = us-central1-a
[core]
account = bob@foo.com
disable_usage_reporting = false
project = mineral-minutia-820
Your active configuration is: [default]
```


````bash
$ docker run --rm -it -v $HOME/.config/:/.config/ salrashid123/cloud-sdk-docker gsutil ls gs://mineral-minutia-820/
gs://mineral-minutia-820/output-00000-of-00009
gs://mineral-minutia-820/output-00001-of-00009
```

**Comment by ahmetb** [comment]
`--volumes-from` is fine, so let's keep it.
