### ISSUE TITLE
Bigtable Emulator image

### ISSUE THREAD

**Issue by wwkeyboard** [GoogleCloudPlatform/cloud-sdk-docker#69]
It would be useful for testing if the bigtable emulator were distributed as an image. Something along the lines of:

```
FROM google/cloud-sdk

EXPOSE 8086

CMD ["gcloud", "beta", "emulators", "bigtable", "start"]
```

**Comment by ahmetb** [comment]
We're not publishing additional components in the images, you can extend the image yourself as you described above however.

See https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/457f507125519d4051cf34d045cd396fafd0bba6/google_appengine_base/Dockerfile which has some bigtable bits (now archived) and read this section: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/tree/457f507125519d4051cf34d045cd396fafd0bba6#installing-additional-components
