### ISSUE TITLE
Deleting Image from GCR returns code 1 which crashes CI

### ISSUE THREAD

**Issue by lihan** [GoogleCloudPlatform/cloud-sdk-docker#71]
`yes Y | gcloud container images delete gcr.io/awesome-project/example-image`
Executing this command will result in a return code of `1` instad of `0` even if the command succeeded.
When this is used in `CI`, the `CI` pipeline will stop because of this.

Also, can `gcloud container images delete` support non-interactive(unattended) way to delete an image?

**Comment by ahmetb** [comment]
You can use `gcloud container images delete -q` flag to run the command in unattended way.

Does `yes Y | gcloud container images delete gcr.io/awesome-project/example-image` fail on your local machine as well, or is it just the Docker image?

**Comment by ahmetb** [comment]
I'll close this soon if there's no new activity.
