### ISSUE TITLE
Have a root Dockerfile

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-sdk-docker#72]
@salrashid123 we should have a preferred Dockerfile on the repository root. Currently it's not clear which one is the preferred one. We can do this by symlinking. Can you send a patch? Sorry I didn't catch this during the code review.

**Comment by salrashid123** [comment]
in [PR#73](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/73)
