### ISSUE TITLE
'compute ssh' gives error   

### ISSUE THREAD

**Issue by lokee103** [GoogleCloudPlatform/cloud-sdk-docker#76]
With the latest build executing `docker run -ti  google/cloud-sdk:latest gcloud compute --project ...` returns error `ERROR: (gcloud.compute.ssh) Your platform does not support SSH.`

**Comment by ahmetb** [comment]
This is similar to #56. It looks like maybe we should install the client-side ssh inside the Docker images @salrashid123 ?

**Comment by salrashid123** [comment]
We added in the ssh client in PR https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/87
