### ISSUE TITLE
install kubectl fails

### ISSUE THREAD

**Issue by ValentinRueda** [GoogleCloudPlatform/cloud-sdk-docker#79]
Hello, 

I'm running the latest version of the image `google/cloud-sdk:159.0.0` or using `google/cloud-sdk` 

And `gcloud components install kubectl` fails with 

> You cannot perform this action because this Cloud SDK installation is 
> managed by an external package manager.  If you would like to get the 
> latest version, please see our main download page at:
>   
> https://cloud.google.com/sdk/
> 
> ERROR: (gcloud.components.install) The component manager is disabled for this installation

`gcloud components install kubectl -q --no-user-output-enabled`  doesn't help 

`gcloud components list` gives this

> Your current Cloud SDK version is: 159.0.0
> The latest available version is: 159.0.0
> 
> +-------------------------------------------------------------------------------------------------------------+
> |                                                  Components                                                 |
> +---------------+------------------------------------------------------+--------------------------+-----------+
> |     Status    |                         Name                         |            ID            |    Size   |
> +---------------+------------------------------------------------------+--------------------------+-----------+
> | Not Installed | Cloud Bigtable Command Line Tool                     | cbt                      |   4.1 MiB |
> | Not Installed | Cloud Datastore Emulator (Legacy)                    | gcd-emulator             |  38.1 MiB |
> | Not Installed | Emulator Reverse Proxy                               | emulator-reverse-proxy   |  14.5 MiB |
> | Not Installed | Google Container Registry's Docker credential helper | docker-credential-gcr    |   2.2 MiB |
> | Not Installed | kubectl                                              | kubectl                  |  14.9 MiB |
> | Installed     | App Engine Go Extensions                             | app-engine-go            |  97.0 MiB |
> | Installed     | BigQuery Command Line Tool                           | bq                       |   < 1 MiB |
> | Installed     | Cloud Bigtable Emulator                              | bigtable                 |   3.5 MiB |
> | Installed     | Cloud Datalab Command Line Tool                      | datalab                  |   < 1 MiB |
> | Installed     | Cloud Datastore Emulator                             | cloud-datastore-emulator |  15.4 MiB |
> | Installed     | Cloud Pub/Sub Emulator                               | pubsub-emulator          |  21.0 MiB |
> | Installed     | Cloud SDK Core Libraries                             | core                     |   6.2 MiB |
> | Installed     | Cloud Storage Command Line Tool                      | gsutil                   |   2.9 MiB |
> | Installed     | Default set of gcloud commands                       | gcloud                   |           |
> | Installed     | gcloud Alpha Commands                                | alpha                    |   < 1 MiB |
> | Installed     | gcloud Beta Commands                                 | beta                     |   < 1 MiB |
> | Installed     | gcloud app Java Extensions                           | app-engine-java          | 132.2 MiB |
> | Installed     | gcloud app Python Extensions                         | app-engine-python        |   6.4 MiB |
> +---------------+------------------------------------------------------+--------------------------+-----------+

The expected behaviour is to install the kubectl command, isn't it? 

Thanks, 
Valentin

**Comment by ValentinRueda** [comment]
Tried to create a docker image, but can't build it

> FROM google/cloud-sdk
> RUN gcloud components install kubectl 
and 
> FROM google/cloud-sdk
> RUN gcloud components install kubectl -q --no-user-output-enabled

Fails with 

> Step 1/2 : FROM google/cloud-sdk
>  ---> 7d870e7e0638
> Step 2/2 : RUN gcloud components install kubectl
>  ---> Running in 5216989405ee
> You cannot perform this action because this Cloud SDK installation is 
> managed by an external package manager.  If you would like to get the 
> latest version, please see our main download page at:
>   
> https://cloud.google.com/sdk/
> 
> ERROR: (gcloud.components.install) The component manager is disabled for this installation

**Comment by kilianc** [comment]
I think something changed recently, and the content/behavior of this image is now drastically different. `/.kube` now is at `/root/.kube` and while yesterday I was able to install `kubectl` following the instructions in the readme today I can't (and the readme seems to have been updated accordingly).

What is the best approach to use GKE / Kubectl in a Docker based CI environment ?

**Comment by tmegow** [comment]
Today I pulled the google/cloud-sdk:latest image and I can no longer install `kubectl`.
I am also receiving the same error:
`+ gcloud components install kubectl -q --no-user-output-enabled
ERROR: (gcloud.components.install) The component manager is disabled for this installation`

Any ideas how to get kubectl installed in the new image?

**Comment by hgascoigne** [comment]
With the latest version, components must now be installed like other `apt-get` packages. For instance `apt-get install kubectl`. The `kubectl` package, however, is included in the base docker image so you shouldn't need to install it.

**Comment by ahmetb** [comment]
Sorry about the breaking change. Last night we pushed #78 to address complaints at #74. There should be `kubectl` pre-installed now in the `:159.0.0` image already.You don't need to install it again as @hgascoigne said.

Going forward we expect `.kube` path to be at `/root/.kube`. Let me know if this fixes the problem.

**Comment by ValentinRueda** [comment]
Well, I can't find `kubectl` installed
As I mentioned `gcloud components list` returns `| Not Installed | kubectl | kubectl | 14.9 MiB |`

And `kubectl get pods` returns `bash: kubectl: command not found`

**Comment by ahmetb** [comment]
@ValentinRueda that's a bug that we're following up internally. Glad to hear it is working.
