### ISSUE TITLE
Debian 9 as base

### ISSUE THREAD

**Issue by makered** [GoogleCloudPlatform/cloud-sdk-docker#93]
Are there plans to upgrade to `debian:stretch` as base by chance? Python `2.7.9` included with jessie is somewhat dated now and compiling `2.7.13` from scratch followed by `make altinstall` is painful.

Thank you

**Comment by ahmetb** [comment]
@makered Do you mind explaining why do you need the newer version of Python? Are you using this image to run Python programs other than gcloud?

**Comment by makered** [comment]
Just gcloud. We received reports of SSL cert errors that were solved by upgrading Python but later it was revealed that only users running gcloud natively on MacOS with brew installed Python were affected. So apologies, false alarm.

**Comment by ahmetb** [comment]
No worries. The jessie still has EOL at June 2018 to LTS until April 2020, but we would probably upgrade before that.
